export interface SchoolEntry {
  id: string;
  school_name: string;
  village: string;
  taluka: string;
  district: string;
  state: string;
}

export const SCHOOLS_DATA: SchoolEntry[] = [
  { id: "s-1", school_name: "Community center", village: "Surangali", taluka: "Bhokardhan", district: "Jalna", state: "Maharashtra" },
  { id: "s-2", school_name: "G.S Choudhari School", village: "Varangaon", taluka: "Bhusawal", district: "Jalgaon", state: "Maharashtra" },
  { id: "s-3", school_name: "Z.P. School Vangani", village: "Vangani", taluka: "Ambernath", district: "Thane", state: "Maharashtra" },
  { id: "s-4", school_name: "Z.P.School Chikatgaon", village: "Chikatgaon", taluka: "Vaijapur", district: "Chh.Sambhajinagar", state: "Maharashtra" },
  { id: "s-5", school_name: "Z.P.School Chorwaghalgaon", village: "Chorwaghalgaon", taluka: "Vaijapur", district: "Chh.Sambhajinagar", state: "Maharashtra" },
  { id: "s-6", school_name: "Z.P School, Badakwasti", village: "Palshi", taluka: "Sillod", district: "Chh.Sambhajinagar", state: "Maharashtra" },
  { id: "s-7", school_name: "Balpan School, Panodi", village: "Panodi", taluka: "Sangamner", district: "Ahmednagar", state: "Maharashtra" },
  { id: "s-8", school_name: "Z.P.School Kalegaon", village: "Kalegaon", taluka: "Khamgaon", district: "Buldhana", state: "Maharashtra" },
  { id: "s-9", school_name: "Z.P School, Kumbefal", village: "Kumbefal", taluka: "Khamgaon", district: "Buldhana", state: "Maharashtra" },
  { id: "s-10", school_name: "Z.P School, Antradneed, Neral", village: "Antrad Need", taluka: "Karjat", district: "Raigad", state: "Maharashtra" },
  { id: "s-11", school_name: "Z.P School, Aswalamba", village: "Aswalamba", taluka: "Parli", district: "Beed", state: "Maharashtra" },
  { id: "s-12", school_name: "Z.P School, Samrala", village: "Samrala", taluka: "Dharmabad", district: "Nanded", state: "Maharashtra" },
  { id: "s-13", school_name: "Z.P School, Rumhana", village: "Rumhana", taluka: "Sindhkhedraja", district: "Buldhana", state: "Maharashtra" },
  { id: "s-14", school_name: "Z.P School, Gajanan Nagar", village: "Nillod", taluka: "Sillod", district: "Chh.Sambhajinagar", state: "Maharashtra" },
  { id: "s-15", school_name: "Z.P School, Mahalgaon", village: "Mahalgaon", taluka: "Vaijapur", district: "Chh.Sambhajinagar", state: "Maharashtra" },
  { id: "s-16", school_name: "Z.P School, Poshir", village: "Poshir", taluka: "Karjat", district: "Raigad", state: "Maharashtra" },
  { id: "s-17", school_name: "Z.P School, Kalyachi Wadi", village: "Kalyachi Wadi", taluka: "Karjat", district: "Raigad", state: "Maharashtra" },
  { id: "s-18", school_name: "Z.P School, Devlipada", village: "Devlipada", taluka: "Shahapur", district: "Thane", state: "Maharashtra" },
  { id: "s-19", school_name: "Z.P School, Pashtepada", village: "Pashtepada", taluka: "Shahapur", district: "Thane", state: "Maharashtra" },
  { id: "s-20", school_name: "Z.P School, Gohre Budruk", village: "Gohre Budruk", taluka: "Haveli", district: "Pune", state: "Maharashtra" },
  { id: "s-21", school_name: "Z.P School Mandwa", village: "Mandwa", taluka: "Parli", district: "Beed", state: "Maharashtra" },
  { id: "s-22", school_name: "Adarsh Vidyalya, Mandwa", village: "Mandwa", taluka: "Parli", district: "Beed", state: "Maharashtra" },
  { id: "s-23", school_name: "Z.P School Mirwat", village: "Mirwat", taluka: "Parli", district: "Beed", state: "Maharashtra" },
  { id: "s-24", school_name: "Z.P School, Kasarwadi", village: "Kasarwadi", taluka: "Parli", district: "Beed", state: "Maharashtra" },
  { id: "s-25", school_name: "Sant.Janabai Vidyalya, Gangakhed", village: "Gangakhed", taluka: "Gangakhed", district: "Parbhani", state: "Maharashtra" },
  { id: "s-26", school_name: "Z.P School, Ambivali", village: "Ambivali", taluka: "Karjat", district: "Raigad", state: "Maharashtra" },
  { id: "s-27", school_name: "Z.P.School, Palaskheda Murtad", village: "Palaskheda Murtad", taluka: "Bhokardhan", district: "Jalna", state: "Maharashtra" },
  { id: "s-28", school_name: "Z.P.School Zavkheda Thombre", village: "Zavkheda Thombre", taluka: "Bhokardhan", district: "Jalna", state: "Maharashtra" },
  { id: "s-29", school_name: "Z.P School, Indapwadi", village: "Indapwadi", taluka: "Parli", district: "Beed", state: "Maharashtra" },
  { id: "s-30", school_name: "Z.P School, Chandai Khurd", village: "Chandai Khurd", taluka: "Karjat", district: "Raigad", state: "Maharashtra" },
  { id: "s-31", school_name: "Z.P.School, Mamdapur", village: "Mamdapur", taluka: "Parli", district: "Beed", state: "Maharashtra" },
  { id: "s-32", school_name: "Ashram Shala, Kaudgaon Huda", village: "Kaudgaon Ghoda", taluka: "Parli", district: "Beed", state: "Maharashtra" },
  { id: "s-33", school_name: "Z.P School, Jambergaon", village: "Jambergaon", taluka: "Vaijapur", district: "Chh.Sambhajinagar", state: "Maharashtra" },
  { id: "s-34", school_name: "Z.P. School, Sayala", village: "Sayala", taluka: "Palam", district: "Parbhani", state: "Maharashtra" },
  { id: "s-35", school_name: "Z.P. School, Bastwad", village: "Bastwad", taluka: "Shirol", district: "Kolhapur", state: "Maharashtra" },
  { id: "s-36", school_name: "Z.P. School, Majrewadi", village: "Majrewadi", taluka: "Shirol", district: "Kolhapur", state: "Maharashtra" },
  { id: "s-37", school_name: "Z.P. School, Rajapurwadi", village: "Rajapurwadi", taluka: "Shirol", district: "Kolhapur", state: "Maharashtra" },
  { id: "s-38", school_name: "Z.P. School, Antrat Varedi", village: "Antrat Varedi", taluka: "Karjat", district: "Raigad", state: "Maharashtra" },
  { id: "s-39", school_name: "Z.P. School, Lakhanwada", village: "Lakhanwada", taluka: "Khamgaon", district: "Buldhana", state: "Maharashtra" },
  { id: "s-40", school_name: "Z.P. School, Bothakazi", village: "Bothakazi", taluka: "Khamgaon", district: "Buldhana", state: "Maharashtra" },
  { id: "s-41", school_name: "Z.P. School Malisagaj", village: "Malisagaj", taluka: "Vaijapur", district: "Chh.Sambhajinagar", state: "Maharashtra" },
  { id: "s-42", school_name: "Z.P. School Bhagur", village: "Bhagur", taluka: "Vaijapur", district: "Chh.Sambhajinagar", state: "Maharashtra" },
  { id: "s-43", school_name: "Z.P School, Malyan, Dahanu", village: "Malyan", taluka: "Dahanu", district: "Palghar", state: "Maharashtra" },
  { id: "s-44", school_name: "Z.P School Vadkun Dandipada", village: "Vadkun Dandipada", taluka: "Dahanu", district: "Palghar", state: "Maharashtra" },
  { id: "s-45", school_name: "Z.P.School, Narpad", village: "Narpad", taluka: "Dahanu", district: "Palghar", state: "Maharashtra" },
  { id: "s-46", school_name: "Z.P School Badapokhran", village: "Badapokhran", taluka: "Dahanu", district: "Palghar", state: "Maharashtra" },
  { id: "s-47", school_name: "Z.P School Varor", village: "Pavalepada, Varor", taluka: "Dahanu", district: "Palghar", state: "Maharashtra" },
  { id: "s-48", school_name: "Z.P Girls School, Satpati", village: "Satpati", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-49", school_name: "Z.P School Urdu, Satpati", village: "Satpati", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-50", school_name: "Z.P School, Satpati", village: "Satpati", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-51", school_name: "Z.P.School Vadrai", village: "Vadrai", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-52", school_name: "Z.P. School, Devpada", village: "Devpada", taluka: "Karjat", district: "Raigad", state: "Maharashtra" },
  { id: "s-53", school_name: "Z.P School, Eknathwadi", village: "Eknathwadi", taluka: "Karjat", district: "Raigad", state: "Maharashtra" },
  { id: "s-54", school_name: "Prithviraj Kapoor Highschool", village: "Lonikalbhor", taluka: "Haveli", district: "Pune", state: "Maharashtra" },
  { id: "s-55", school_name: "R.Z.P. School Mandave", village: "Mandve", taluka: "Alibag", district: "Raigad", state: "Maharashtra" },
  { id: "s-56", school_name: "Z.School Zalanwadi", village: "Zalanwadi", taluka: "Haveli", district: "Pune", state: "Maharashtra" },
  { id: "s-57", school_name: "Shakuntalabai Shitole School", village: "Sangvi", taluka: "Haveli", district: "Pune", state: "Maharashtra" },
  { id: "s-58", school_name: "R.Z.P. School, Wakas", village: "Wakas", taluka: "Karjat", district: "Raigad", state: "Maharashtra" },
  { id: "s-59", school_name: "R.Z.P.School Newali", village: "Newali", taluka: "Karjat", district: "Raigad", state: "Maharashtra" },
  { id: "s-60", school_name: "Z.P School, Chinchwad Goan", village: "Chinchwadgoan", taluka: "Vaijapur", district: "Chh.Sambhajinagar", state: "Maharashtra" },
  { id: "s-61", school_name: "Patit Pawan Vidhyamandir, Ozarde", village: "Ozarde", taluka: "Wai", district: "Satara", state: "Maharashtra" },
  { id: "s-62", school_name: "Z.P. School Aadhe", village: "Aadhe", taluka: "Haveli", district: "Pune", state: "Maharashtra" },
  { id: "s-63", school_name: "Z.P. School, Vadu Khurd", village: "Vadu Khurd", taluka: "Haveli", district: "Pune", state: "Maharashtra" },
  { id: "s-64", school_name: "Z.P School, Nadhi", village: "Nadhi", taluka: "Vaijapur", district: "Chh.Sambhajinagar", state: "Maharashtra" },
  { id: "s-65", school_name: "Z.P. School, AgarSaigoan", village: "Agarsaigoan", taluka: "Vaijapur", district: "Chh.Sambhajinagar", state: "Maharashtra" },
  { id: "s-66", school_name: "Z.P.School Bakori", village: "Bakori", taluka: "Haveli", district: "Pune", state: "Maharashtra" },
  { id: "s-67", school_name: "Z.P. School Lonikalbhor", village: "Lonikalbhor", taluka: "Haveli", district: "Pune", state: "Maharashtra" },
  { id: "s-68", school_name: "Pareshwar Vidhyalay, Pargoan Memane", village: "Pargoan Memane", taluka: "Purandhar", district: "Pune", state: "Maharashtra" },
  { id: "s-69", school_name: "Z.P.School Lonikand", village: "Lonikand", taluka: "Haveli", district: "Pune", state: "Maharashtra" },
  { id: "s-70", school_name: "Madh Municipal School", village: "Madh Beach", taluka: "Malad", district: "Mumbai", state: "Maharashtra" },
  { id: "s-71", school_name: "Erangal Municipal School", village: "Erangal Beach", taluka: "Malad", district: "Mumbai", state: "Maharashtra" },
  { id: "s-72", school_name: "Gorai Municipal School", village: "Gorai Beach", taluka: "Malad", district: "Mumbai", state: "Maharashtra" },
  { id: "s-73", school_name: "Z.P. School Arnala Fort", village: "Arnala Killa", taluka: "Vasai", district: "Palghar", state: "Maharashtra" },
  { id: "s-74", school_name: "Z.P.School Arnala Village", village: "Arnala", taluka: "Vasai", district: "Palghar", state: "Maharashtra" },
  { id: "s-75", school_name: "Z.P. School Edwan", village: "Edwan", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-76", school_name: "Z.P. School Mahim Gavrai", village: "Mahim", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-77", school_name: "Z.P.School Mahim Tembhi", village: "Mahim Tembhi", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-78", school_name: "Z.P.School Kharekuran", village: "Kharekuran", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-79", school_name: "Z.P. School, Uchheli", village: "Uccheli", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-80", school_name: "Z.P. School Dhakti Dahanu", village: "Dhakti Dahanu", taluka: "Dahanu", district: "Palghar", state: "Maharashtra" },
  { id: "s-81", school_name: "Z.P. School, Dahanu No.2", village: "Dahanu No 2", taluka: "Dahanu", district: "Palghar", state: "Maharashtra" },
  { id: "s-82", school_name: "Z.P. School, Dahanu Agar", village: "Dahanu Agar", taluka: "Dahanu", district: "Palghar", state: "Maharashtra" },
  { id: "s-83", school_name: "Z.P.School Malwandi Dhore", village: "Malvandi", taluka: "Haveli", district: "Pune", state: "Maharashtra" },
  { id: "s-84", school_name: "Z.P. School Sadavli", village: "Sadavli", taluka: "Haveli", district: "Pune", state: "Maharashtra" },
  { id: "s-85", school_name: "Z.P.School Ozarde", village: "Ozarde", taluka: "Haveli", district: "Pune", state: "Maharashtra" },
  { id: "s-86", school_name: "Z.P.School Mhaskewasti Shivane", village: "Shivane", taluka: "Haveli", district: "Pune", state: "Maharashtra" },
  { id: "s-87", school_name: "Z.P.School Kankwadi", village: "Kankwadi", taluka: "Haveli", district: "Pune", state: "Maharashtra" },
  { id: "s-88", school_name: "Z.P.School Shivne", village: "Shivane", taluka: "Haveli", district: "Pune", state: "Maharashtra" },
  { id: "s-89", school_name: "Z.P.School Bramhanwadi", village: "Bramhanwadi (Baur)", taluka: "Haveli", district: "Pune", state: "Maharashtra" },
  { id: "s-90", school_name: "Z.P. School Baur", village: "Baur", taluka: "Haveli", district: "Pune", state: "Maharashtra" },
  { id: "s-91", school_name: "Z.P.School Thugaon", village: "Thugaon", taluka: "Haveli", district: "Pune", state: "Maharashtra" },
  { id: "s-92", school_name: "Z.P.School Chandkhed", village: "Chandkhed", taluka: "Haveli", district: "Pune", state: "Maharashtra" },
  { id: "s-93", school_name: "Z.P.School Dhamani", village: "Dhamne", taluka: "Haveli", district: "Pune", state: "Maharashtra" },
  { id: "s-94", school_name: "Z.P.School Urse", village: "Urse", taluka: "Haveli", district: "Pune", state: "Maharashtra" },
  { id: "s-95", school_name: "Z.P.School Parandwadi", village: "Parandwadi", taluka: "Haveli", district: "Pune", state: "Maharashtra" },
  { id: "s-96", school_name: "Z.P.School Ghaigaon", village: "Ghaigaon", taluka: "Vaijapur", district: "Chh.Sambhajinagar", state: "Maharashtra" },
  { id: "s-97", school_name: "Netaji Subhash Vidyalay Pathri", village: "Pathri", taluka: "Pathri", district: "Parbhani", state: "Maharashtra" },
  { id: "s-98", school_name: "Z.P.School Posari", village: "Posari", taluka: "Karjat", district: "Raigad", state: "Maharashtra" },
  { id: "s-99", school_name: "Z.P. School Koliwali", village: "Koliwali", taluka: "Karjat", district: "Raigad", state: "Maharashtra" },
  { id: "s-100", school_name: "R.Z.P.School Pimploli", village: "Pimploli", taluka: "Karjat", district: "Raigad", state: "Maharashtra" },
  { id: "s-101", school_name: "Z.P.School Jagadambanagar", village: "Jagdambanagar", taluka: "Omerga", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-102", school_name: "Z.P.School Bet Jawalga", village: "Jawalga", taluka: "Omerga", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-103", school_name: "Z.P.School Dalimb", village: "Dalimb", taluka: "Omerga", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-104", school_name: "Z.P.School Yeli", village: "Yeli", taluka: "Omerga", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-105", school_name: "Z.P.School Samudral", village: "Samudral", taluka: "Omerga", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-106", school_name: "Sanskar Vidhyapeeth, Ramzanwadi", village: "Ramjanwadi", taluka: "Vapi", district: "Valsad", state: "Gujarat" },
  { id: "s-107", school_name: "Govt School Salvav", village: "Salvav", taluka: "Vapi", district: "Valsad", state: "Gujarat" },
  { id: "s-108", school_name: "Bhavnaben Naginbhai Patel School", village: "Salvav Koliwad", taluka: "Vapi", district: "Valsad", state: "Gujarat" },
  { id: "s-109", school_name: "Govt School Azadnagar", village: "Azadnagar", taluka: "Vapi", district: "Valsad", state: "Gujarat" },
  { id: "s-110", school_name: "Nagar Parishad School Karad", village: "Karad", taluka: "Karad", district: "Satara", state: "Maharashtra" },
  { id: "s-111", school_name: "Z.P. School Devrashtre", village: "Devrashtre", taluka: "Sangli", district: "Satara", state: "Maharashtra" },
  { id: "s-112", school_name: "Z.P. School, Temgharwadi", village: "Temgharwadi", taluka: "Khed", district: "Pune", state: "Maharashtra" },
  { id: "s-113", school_name: "Z.P. School, Waki", village: "Waki", taluka: "Khed", district: "Pune", state: "Maharashtra" },
  { id: "s-114", school_name: "Z.P.School Ladwad", village: "Ladwad", taluka: "Khed", district: "Pune", state: "Maharashtra" },
  { id: "s-115", school_name: "Z.P.School Gargoti Shiwar", village: "Gargoti Shivar", taluka: "Khed", district: "Pune", state: "Maharashtra" },
  { id: "s-116", school_name: "Asram Shala Wada", village: "Wada", taluka: "Wada", district: "Palghar", state: "Maharashtra" },
  { id: "s-117", school_name: "Z.P.School Khondoshi", village: "Kondoshi", taluka: "Bhudargad", district: "Kolhapur", state: "Maharashtra" },
  { id: "s-118", school_name: "Z.P. School Bhakaricha Pada", village: "Bhakaricha Pada", taluka: "Karjat", district: "Raigad", state: "Maharashtra" },
  { id: "s-119", school_name: "Z.P.School Pethsangavi", village: "Peth Sangavi", taluka: "Omerga", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-120", school_name: "Z.P.School Mahalingraiwadi", village: "Mahalingraiwadi", taluka: "Omerga", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-121", school_name: "Z.P. School Tugaon", village: "Ujani", taluka: "Omerga", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-122", school_name: "Z.P.School Ukadgaon", village: "Ukadgaon", taluka: "Sonpeth", district: "Parbhani", state: "Maharashtra" },
  { id: "s-123", school_name: "Z.P.School Dagadewadi", village: "Dagadewadi", taluka: "Parali", district: "Beed", state: "Maharashtra" },
  { id: "s-124", school_name: "Dyanbodhini Primary School", village: "Parali Vaijanath", taluka: "Parali", district: "Beed", state: "Maharashtra" },
  { id: "s-125", school_name: "Aadarshya Vidhyalay Mandva", village: "Mandva", taluka: "Parali", district: "Beed", state: "Maharashtra" },
  { id: "s-126", school_name: "Z.P. School Vasahat, Dadahari Vadgaon", village: "Vasahat Vadgaon", taluka: "Parali", district: "Beed", state: "Maharashtra" },
  { id: "s-127", school_name: "Z.P. School Zari", village: "Zari", taluka: "Pathri", district: "Parbhani", state: "Maharashtra" },
  { id: "s-128", school_name: "Z.P.School Waghala", village: "Waghala", taluka: "Pathri", district: "Parbhani", state: "Maharashtra" },
  { id: "s-129", school_name: "Z.P. School Babultar", village: "Babultar", taluka: "Pathri", district: "Parbhani", state: "Maharashtra" },
  { id: "s-130", school_name: "Z.P.School Kutwalwadi", village: "Kutwalwadi", taluka: "Baramati", district: "Pune", state: "Maharashtra" },
  { id: "s-131", school_name: "Z.P. School, Kotbi-Bujadpada", village: "Chari-Kotbi", taluka: "Dahanu", district: "Palghar", state: "Maharashtra" },
  { id: "s-132", school_name: "Z.P. School Chikhle", village: "Chikhle", taluka: "Dahanu", district: "Palghar", state: "Maharashtra" },
  { id: "s-133", school_name: "Z.P. School Vadakati", village: "Vadaktipada", taluka: "Dahanu", district: "Palghar", state: "Maharashtra" },
  { id: "s-134", school_name: "Z.P. School Dhumket", village: "Dhumket", taluka: "Dahanu", district: "Palghar", state: "Maharashtra" },
  { id: "s-135", school_name: "Z.P.School Kharlepada", village: "Kharlepada", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-136", school_name: "Z.P. School Manpada", village: "Manpada", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-137", school_name: "Z.P. School Vikasnagar", village: "Vikas Nagar", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-138", school_name: "Z.P. School, Shegatpada Satpati", village: "Satpati", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-139", school_name: "Urdu School Satpati", village: "Satpati", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-140", school_name: "Shaskiya Matsavyavsay Pri School Satpati", village: "Satpati", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-141", school_name: "Shaskiya Madhyamik Shala Satpati", village: "Satpati", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-142", school_name: "Z.P. School Popharan Dandi", village: "Popharan Dandi", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-143", school_name: "Z.P. School Tembi", village: "Tembhi", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-144", school_name: "Z.P. School Pam", village: "Pam", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-145", school_name: "Z.P. School, Murbe", village: "Murbe", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-146", school_name: "Z.P. School Navapur", village: "Navapur", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-147", school_name: "Z.P. School Ambedkar Nagar", village: "Ambedkar Nagar", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-148", school_name: "Z.P. School, Ghivali", village: "Ghivali", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-149", school_name: "Z.P.School Chikhal Dongare", village: "Chikhal Dongari", taluka: "Vasai", district: "Palghar", state: "Maharashtra" },
  { id: "s-150", school_name: "Z.P. School Kasrali", village: "Kasrali", taluka: "Vasai", district: "Palghar", state: "Maharashtra" },
  { id: "s-151", school_name: "Z.P. School Dahisar", village: "Dahisar", taluka: "Vasai", district: "Palghar", state: "Maharashtra" },
  { id: "s-152", school_name: "Z.P. School Mazgaon", village: "Mazgaon", taluka: "Murud", district: "Raigad", state: "Maharashtra" },
  { id: "s-153", school_name: "R.Z.P.School Nandgaon No.3", village: "Nandgaon", taluka: "Murud", district: "Raigad", state: "Maharashtra" },
  { id: "s-154", school_name: "R.Z.P.School Nandgaon No.1", village: "Nandgaon", taluka: "Murud", district: "Raigad", state: "Maharashtra" },
  { id: "s-155", school_name: "R.Z.P.School Aadad", village: "Adad", taluka: "Murud", district: "Raigad", state: "Maharashtra" },
  { id: "s-156", school_name: "R.Z.P.School Bhoste", village: "Bhoste", taluka: "Shrivardhan", district: "Raigad", state: "Maharashtra" },
  { id: "s-157", school_name: "R.Z.P.School Jaswali Marathi", village: "Jasavli", taluka: "Shrivardhan", district: "Raigad", state: "Maharashtra" },
  { id: "s-158", school_name: "R.Z.P.School Urdu Arathi", village: "Arathi", taluka: "Shrivardhan", district: "Raigad", state: "Maharashtra" },
  { id: "s-159", school_name: "R.Z.P.School Nhave", village: "Nhave", taluka: "Panvel", district: "Raigad", state: "Maharashtra" },
  { id: "s-160", school_name: "R.Z.P. School & Primary School Nhave Khadi", village: "Nhave Khadi", taluka: "Panvel", district: "Raigad", state: "Maharashtra" },
  { id: "s-161", school_name: "Z.P. School Kevale", village: "Kevale", taluka: "Panvel", district: "Raigad", state: "Maharashtra" },
  { id: "s-162", school_name: "Z.P. School Shivkar", village: "Shivkar", taluka: "Panvel", district: "Raigad", state: "Maharashtra" },
  { id: "s-163", school_name: "Z.P. School Kalundre", village: "Kalundre", taluka: "Panvel", district: "Raigad", state: "Maharashtra" },
  { id: "s-164", school_name: "Kendriya Vidhyalay, Panvel", village: "ONGC Colony", taluka: "Panvel", district: "Raigad", state: "Maharashtra" },
  { id: "s-165", school_name: "Z.P. School Deshmukh Takali", village: "Deshmukh", taluka: "Parali", district: "Beed", state: "Maharashtra" },
  { id: "s-166", school_name: "Z.P.School Aaswalamba Tanda", village: "Aswalamba Tanda", taluka: "Parali", district: "Beed", state: "Maharashtra" },
  { id: "s-167", school_name: "Z.P.School Wadgaon Dadhari", village: "Wadgaon Dadahari", taluka: "Parli", district: "Beed", state: "Maharashtra" },
  { id: "s-168", school_name: "Z.P.School Dharmapuri", village: "Dharmapuri", taluka: "Parali", district: "Beed", state: "Maharashtra" },
  { id: "s-169", school_name: "Z.P. School Pimpri Bk", village: "Pimpri Bk", taluka: "Parali", district: "Beed", state: "Maharashtra" },
  { id: "s-170", school_name: "Z.P. School Panshet", village: "Panshet", taluka: "Haveli", district: "Pune", state: "Maharashtra" },
  { id: "s-171", school_name: "Z.P. School Nanegaon", village: "Nanegaon", taluka: "Paithan", district: "Chh.Sambhajinagar", state: "Maharashtra" },
  { id: "s-172", school_name: "Z.P.School Pashta", village: "Pashta", taluka: "Jalna", district: "Jalna", state: "Maharashtra" },
  { id: "s-173", school_name: "Z.P.School Malnathpur", village: "Malnathpur", taluka: "Parali", district: "Beed", state: "Maharashtra" },
  { id: "s-174", school_name: "Z.P. School Perne", village: "Perne", taluka: "Haveli", district: "Pune", state: "Maharashtra" },
  { id: "s-175", school_name: "Kai. Lala Patil Phad Highschool Ghatsawali", village: "Ghatsawali", taluka: "Beed", district: "Beed", state: "Maharashtra" },
  { id: "s-176", school_name: "Z.P. School Pargaon Memane", village: "Pargaon Memane", taluka: "Purandhar", district: "Pune", state: "Maharashtra" },
  { id: "s-177", school_name: "Panchakrishi Shetkari Vidhyalay, Waghapur", village: "Waghapur", taluka: "Purandhar", district: "Pune", state: "Maharashtra" },
  { id: "s-178", school_name: "Z.P.School Malegaon", village: "Malegaon", taluka: "Haveli", district: "Pune", state: "Maharashtra" },
  { id: "s-179", school_name: "Z.P.School Kajala", village: "Kajala", taluka: "Dharashiv", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-180", school_name: "Z.P.School Ghatangri", village: "Ghatangri", taluka: "Dharashiv", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-181", school_name: "Z.P.School Varuda", village: "Varuda", taluka: "Dharashiv", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-182", school_name: "Z.P.Girls School Kond", village: "Kond", taluka: "Dharashiv", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-183", school_name: "Z.P.School Tugaon", village: "Tugaon", taluka: "Dharashiv", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-184", school_name: "Z.P.School Kasai", village: "Kasai", taluka: "Tuljapur", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-185", school_name: "Z.P.School Pimpla Khurd", village: "Pimpla Khurd", taluka: "Tuljapur", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-186", school_name: "Z.P.School Sindgaon", village: "Sindgaon", taluka: "Tuljapur", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-187", school_name: "Z.P.School Yevti", village: "Yevti", taluka: "Tuljapur", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-188", school_name: "Z.P.School Keshgaon", village: "Keshgaon", taluka: "Tuljapur", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-189", school_name: "Z.P.School Peth Ter", village: "Peth Ter", taluka: "Dharashiv", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-190", school_name: "Z.P.School Aalni", village: "Aalni", taluka: "Dharashiv", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-191", school_name: "Z.P.School Takviki", village: "Takviki", taluka: "Dharashiv", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-192", school_name: "Z.P.School Karanjkheda", village: "Karanjkheda", taluka: "Dharashiv", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-193", school_name: "Z.P.School Nandurga", village: "Nandurga", taluka: "Dharashiv", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-194", school_name: "Z.P.School Kijal", village: "Kijal", taluka: "Tuljapur", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-195", school_name: "Z.P.School Raikhel", village: "Raikhel", taluka: "Tuljapur", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-196", school_name: "Z.P.School Khudawadi", village: "Khudawadi", taluka: "Tuljapur", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-197", school_name: "Z.P.School Raghuchiwadi", village: "Raghuchiwadi", taluka: "Dharashiv", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-198", school_name: "Z.P.School Devlali", village: "Devlali", taluka: "Dharashiv", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-199", school_name: "Z.P.School Kakramba", village: "Kakramba", taluka: "Tuljapur", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-200", school_name: "Z.P.School Khemwadi", village: "Khemwadi", taluka: "Tuljapur", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-201", school_name: "Z.P.School Nilegaon", village: "Nilegaon", taluka: "Tuljapur", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-202", school_name: "Z.P.School Horti", village: "Horti", taluka: "Tuljapur", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-203", school_name: "Z.P.School Jalkot", village: "Jalkot", taluka: "Tuljapur", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-204", school_name: "Z.P.School Manglur", village: "Manglur", taluka: "Kalamb", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-205", school_name: "Z.P.School Bhatshirpura", village: "Bhatshirpura", taluka: "Kalamb", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-206", school_name: "Z.P.School Babhalgaon", village: "Babhalgaon", taluka: "Kalamb", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-207", school_name: "Z.P.School Uplai", village: "Uplai", taluka: "Kalamb", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-208", school_name: "Z.P.School Pimpri Shirdhon", village: "Pimpri Shirdhon", taluka: "Kalamb", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-209", school_name: "Z.P.School Bavi", village: "Bavi", taluka: "Washi", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-210", school_name: "Z.P.Girls School Terkheda", village: "Terkheda", taluka: "Washi", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-211", school_name: "Z.P.School Kanheri", village: "Kanheri", taluka: "Washi", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-212", school_name: "Z.P.School Pimpalwadi", village: "Pimpalwadi", taluka: "Paranda", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-213", school_name: "Z.P.School Takali", village: "Takali", taluka: "Paranda", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-214", school_name: "Z.P.School Shirala", village: "Shirala", taluka: "Paranda", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-215", school_name: "Z.P.School Ghargaon", village: "Ghargaon", taluka: "Paranda", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-216", school_name: "Z.P.School Devgaon Budruk", village: "Devgaon Budruk", taluka: "Paranda", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-217", school_name: "Z.P.School Shelgaon", village: "Shelgaon", taluka: "Paranda", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-218", school_name: "Z.P.School Jewali (South)", village: "Jewali (South)", taluka: "Lohara", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-219", school_name: "Z.P.School Rajegaon", village: "Rajegaon", taluka: "Lohara", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-220", school_name: "Z.P.School Bhosga", village: "Bhosga", taluka: "Lohara", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-221", school_name: "Z.P.School Hipparga Rava", village: "Hipparga Rava", taluka: "Lohara", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-222", school_name: "Z.P.School Aarsoli", village: "Aarsoli", taluka: "Bhoom", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-223", school_name: "Z.P.School Walha", village: "Walha", taluka: "Bhoom", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-224", school_name: "Z.P.School Chincholi", village: "Chincholi", taluka: "Bhoom", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-225", school_name: "Z.P.School Tintraj", village: "Tintraj", taluka: "Bhoom", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-226", school_name: "Z.P.School Nipani", village: "Nipani", taluka: "Bhoom", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-227", school_name: "Z.P.School Trikoli", village: "Trikoli", taluka: "Omerga", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-228", school_name: "Z.P.School Belamb", village: "Belamb", taluka: "Omerga", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-229", school_name: "Z.P.School Koral", village: "Koral", taluka: "Omerga", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-230", school_name: "Z.P.School Aashta", village: "Aashta", taluka: "Omerga", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-231", school_name: "Z.P.School Balsur", village: "Balsur", taluka: "Omerga", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-232", school_name: "Mahatma Phule Vidyalay Khodad", village: "Khodad", taluka: "Junnar", district: "Pune", state: "Maharashtra" },
  { id: "s-233", school_name: "Z.P.School Hanuman Nagar", village: "Shigaon", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-234", school_name: "Z.P.School Katkaripada", village: "Haloli", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-235", school_name: "Z.P.School Velgaon", village: "Manor", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-236", school_name: "Z.P.School Devulpada", village: "Chahade", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-237", school_name: "Z.P.School Chalani Tivaspada", village: "Saiwan", taluka: "Dahanu", district: "Palghar", state: "Maharashtra" },
  { id: "s-238", school_name: "Z.P.School Mahalpada", village: "Ganjad", taluka: "Dahanu", district: "Palghar", state: "Maharashtra" },
  { id: "s-239", school_name: "Z.P.School Vasantvadi", village: "Vasantwadi", taluka: "Dahanu", district: "Palghar", state: "Maharashtra" },
  { id: "s-240", school_name: "Z.P.School Haloli - Padavalpada", village: "Haloli", taluka: "Dahanu", district: "Palghar", state: "Maharashtra" },
  { id: "s-241", school_name: "Z.P.School Kirat", village: "Kirat", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-242", school_name: "Z.P.School Haloli Gavthanpada", village: "Haloli", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-243", school_name: "Z.P.School Bhoirpada", village: "Chahade", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-244", school_name: "Z.P.School Padghe Kolipada", village: "Umroli", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-245", school_name: "Z.P.School Navapada", village: "Navali", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-246", school_name: "Z.P.School Vavepada", village: "Navali", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-247", school_name: "Z.P.School Vakadi", village: "Katale", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-248", school_name: "Z.P.School Kukade", village: "Mahagaon", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-249", school_name: "Z.P.School Nane", village: "Gorhe", taluka: "Wada", district: "Palghar", state: "Maharashtra" },
  { id: "s-250", school_name: "Z.P.School Peth Rajani", village: "Peth Ranjani", taluka: "Wada", district: "Palghar", state: "Maharashtra" },
  { id: "s-251", school_name: "Z.P.School Aaswe Savarpada", village: "Aashagad", taluka: "Dahanu", district: "Palghar", state: "Maharashtra" },
  { id: "s-252", school_name: "Z.P.School Aamgaon Thakarpada", village: "Aamgaon", taluka: "Talasari", district: "Palghar", state: "Maharashtra" },
  { id: "s-253", school_name: "Z.P.School Nihe", village: "Katale", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-254", school_name: "Z.P.School Vandivali", village: "Vandivali", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-255", school_name: "Z.P.School Aakegavhan", village: "Kirat", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-256", school_name: "Z.P.School Haloli", village: "Haloli", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-257", school_name: "Z.P.School Lalthane", village: "Lalthane", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-258", school_name: "GOVT. Aashram School Takvhal", village: "Manor", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-259", school_name: "Z.P.School Masvan", village: "Maswan", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-260", school_name: "Z.P.School Valvipada", village: "Valvipada", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-261", school_name: "Z.P.School Panjare", village: "Nagzari", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-262", school_name: "Z.P. School, Gyalanpada", village: "Ganjad", taluka: "Dahanu", district: "Palghar", state: "Maharashtra" },
  { id: "s-263", school_name: "Z.P.School Jamshet Kamdipada", village: "Aashagad", taluka: "Dahanu", district: "Palghar", state: "Maharashtra" },
  { id: "s-264", school_name: "Z.P.School Dabhon Patilpada", village: "Dabhon", taluka: "Dahanu", district: "Palghar", state: "Maharashtra" },
  { id: "s-265", school_name: "Z.P.School Sagdev Khadkipada", village: "Sagdeo", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-266", school_name: "Z.P.School Tambdipada", village: "Chilhar", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-267", school_name: "Z.P.School Tolipada", village: "Chilhar", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-268", school_name: "Z.P.School Davrepada", village: "Chilhar", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-269", school_name: "Z.P.School Gavlipada", village: "Chilhar", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-270", school_name: "Z.P.School Dongarmal", village: "Velgaon", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-271", school_name: "Z.P.School Bhuklepada", village: "Haloli", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-272", school_name: "Z.P.School Kude Patilpada", village: "Haloli", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-273", school_name: "Z.P.School Khadkona", village: "Haloli", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-274", school_name: "Z.P.School Ghatalpada", village: "Haloli", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-275", school_name: "Z.P.School Khutal", village: "Haloli", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-276", school_name: "Z.P.School Dhanvipada", village: "Haloli", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-277", school_name: "ZP Purn Prathamik Adarsh Shala Purngad", village: "Purngad", taluka: "Ratnagiri", district: "Ratnagiri", state: "Maharashtra" },
  { id: "s-278", school_name: "ZP Purn Prathamik Shala Pomendi", village: "Pomendi", taluka: "Ratnagiri", district: "Ratnagiri", state: "Maharashtra" },
  { id: "s-279", school_name: "Z.P.School Astan No.1", village: "Astan", taluka: "Khed", district: "Ratnagiri", state: "Maharashtra" },
  { id: "s-280", school_name: "Z.P.School Bochalpada", village: "Chilhar", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-281", school_name: "ZP Adarsh School Kaluste", village: "Kaluste", taluka: "Chiplun", district: "Ratnagiri", state: "Maharashtra" },
  { id: "s-282", school_name: "Z.P.Adarsh Marathi School Pisai", village: "Pisai", taluka: "Dapoli", district: "Ratnagiri", state: "Maharashtra" },
  { id: "s-283", school_name: "RZP School, Gondghar", village: "Mhasala", taluka: "Mhasala", district: "Raigad", state: "Maharashtra" },
  { id: "s-284", school_name: "Raigad ZP Marathi School Valvati", village: "Vakavati", taluka: "Shrivardhan", district: "Raigad", state: "Maharashtra" },
  { id: "s-285", school_name: "Z.P.School Varoti Valvipada (Kasa)", village: "Kasai", taluka: "Dahanu", district: "Palghar", state: "Maharashtra" },
  { id: "s-286", school_name: "Z.P.School Shiroshi", village: "Shiroshi", taluka: "Jawhar", district: "Palghar", state: "Maharashtra" },
  { id: "s-287", school_name: "Z.P.School Bhatpada", village: "Vasai", taluka: "Vasai", district: "Palghar", state: "Maharashtra" },
  { id: "s-288", school_name: "Z.P.School Gharatpada", village: "Manor", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-289", school_name: "Z.P.School Devkhop Thalekarpada", village: "Devkhop", taluka: "Palghar", district: "Palghar", state: "Maharashtra" },
  { id: "s-290", school_name: "Z.P.School Kesarjawalga", village: "Kesarjawalga", taluka: "Omerga", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-291", school_name: "Z.P.School Talmod", village: "Talmod", taluka: "Omerga", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-292", school_name: "Z.P.School Aanandnagar", village: "Aanandnagar", taluka: "Omerga", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-293", school_name: "Z.P.School Mulaj", village: "Mulaj", taluka: "Omerga", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-294", school_name: "Z.P.School Jagaji", village: "Jagaji", taluka: "Omerga", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-295", school_name: "Z.P.School Omerga", village: "Omerga", taluka: "Omerga", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-296", school_name: "Z.P.School Bhatangli", village: "Bhatangali", taluka: "Omerga", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-297", school_name: "Z.P.School Dhanuri", village: "Dhanuri", taluka: "Lohara", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-298", school_name: "Z.P.School Ieet", village: "Ieet", taluka: "Lohara", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-299", school_name: "Z.P.School Jawala", village: "Jawala", taluka: "Bhoom", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-300", school_name: "Z.P.School Kukkadgaon", village: "Kukkadgaon", taluka: "Paranda", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-301", school_name: "Z.P.School Masala", village: "Masala", taluka: "Paranda", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-302", school_name: "Z.P.School Sonari", village: "Sonari", taluka: "Tuljapur", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-303", school_name: "Z.P.School Patharud", village: "Patharud", taluka: "Paranda", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-304", school_name: "Z.P.School Paranda", village: "Paranda", taluka: "Paranda", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-305", school_name: "Z.P.School Patoda", village: "Patoda", taluka: "Dharashiv", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-306", school_name: "Z.P.School Pargaon", village: "Pargaon", taluka: "Washi", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-307", school_name: "Z.P.School Kaneri", village: "Kaneri", taluka: "Washi", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-308", school_name: "Z.P.School Para", village: "Para", taluka: "Washi", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-309", school_name: "Z.P.School Samarkundi", village: "Samarkundi", taluka: "Washi", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-310", school_name: "Z.P.School Aashta Bhoom", village: "Ashta Bhoom", taluka: "Bhoom", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-311", school_name: "Z.P.School Vadgaon", village: "Vadgaon", taluka: "Dharashiv", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-312", school_name: "Z.P.School Sanja", village: "Sanja", taluka: "Dharashiv", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-313", school_name: "Z.P.School Washi", village: "Washi", taluka: "Washi", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-314", school_name: "Z.P.School Naldurg", village: "Naldurg", taluka: "Tuljapur", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-315", school_name: "Z.P.School Khamaswadi", village: "Khamaswadi", taluka: "Kalamb", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-316", school_name: "Z.P.School Shiradhon", village: "Shiradhon", taluka: "Kalamb", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-317", school_name: "Z.P.School Itkur", village: "Itkur", taluka: "Kalamb", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-318", school_name: "Z.P.School Naigaon", village: "Naigaon", taluka: "Kalamb", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-319", school_name: "Z.P.School Kaudgaon", village: "Kaudgaon", taluka: "Paranda", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-320", school_name: "Z.P.School Govardhanwadi No.1", village: "Govardhanwadi", taluka: "Dharashiv", district: "Dharashiv", state: "Maharashtra" },
  { id: "s-321", school_name: "Z.P. School Ambi", village: "Ambi", taluka: "Haveli", district: "Pune", state: "Maharashtra" },
  { id: "s-322", school_name: "Z.P. School Kashal", village: "Kashal", taluka: "Haveli", district: "Pune", state: "Maharashtra" },
  { id: "s-323", school_name: "Nursinha Highschool, Old Sangvi", village: "Sangvi", taluka: "Haveli", district: "Pune", state: "Maharashtra" },
  { id: "s-324", school_name: "Z.P. School Lonikand", village: "Lonikand", taluka: "Haveli", district: "Pune", state: "Maharashtra" },
  { id: "s-325", school_name: "Basu Vidhyalay Lonikand", village: "Lonikand", taluka: "Haveli", district: "Pune", state: "Maharashtra" },
  { id: "s-326", school_name: "Z.P. School Bakori", village: "Bakori", taluka: "Haveli", district: "Pune", state: "Maharashtra" },
  { id: "s-327", school_name: "Z.P. School Waysewadi", village: "Waysewadi", taluka: "Indapur", district: "Pune", state: "Maharashtra" },
  { id: "s-328", school_name: "Z.P. School Ashoknagar", village: "Ashoknagar", taluka: "Indapur", district: "Pune", state: "Maharashtra" },
  { id: "s-329", school_name: "Z.P. School Mhaski", village: "Mhaski", taluka: "Vaijapur", district: "Chh.Sambhajinagar", state: "Maharashtra" },
  { id: "s-330", school_name: "Z.P. School Talwada", village: "Talwada", taluka: "Vaijapur", district: "Chh.Sambhajinagar", state: "Maharashtra" },
  { id: "s-331", school_name: "Z.P. School Sadegaon", village: "Sadegaon", taluka: "Parbhani", district: "Parbhani", state: "Maharashtra" },
  { id: "s-332", school_name: "Z.P. School Lokarwadi", village: "Lokarwadi", taluka: "Sonpeth", district: "Parbhani", state: "Maharashtra" },
  { id: "s-333", school_name: "Z.P. School Rui(Limba)", village: "Rui Limba", taluka: "Beed", district: "Beed", state: "Maharashtra" },
  { id: "s-334", school_name: "Z.P. School Ashtha Harinarayan", village: "Ashtha Harinarayan", taluka: "Ashti", district: "Beed", state: "Maharashtra" },
  { id: "s-335", school_name: "Z.P. School Daunapur", village: "Daunapur", taluka: "Parli", district: "Beed", state: "Maharashtra" },
  { id: "s-336", school_name: "Z.P. School Nathra", village: "Nathra", taluka: "Parli", district: "Beed", state: "Maharashtra" },
  { id: "s-337", school_name: "Z.P. School, Sakud", village: "Sakud", taluka: "Ambajogai", district: "Beed", state: "Maharashtra" },
  { id: "s-338", school_name: "Z.P. School, Poos", village: "Poos", taluka: "Ambajogai", district: "Beed", state: "Maharashtra" },
  { id: "s-339", school_name: "Z.P. School Maindwadi", village: "Mahindwadi", taluka: "Parali Vaijanath", district: "Beed", state: "Maharashtra" },
  { id: "s-340", school_name: "Z.P. School Khatkewasti", village: "Khatkewasti", taluka: "Phaltan", district: "Satara", state: "Maharashtra" },
  { id: "s-341", school_name: "RZP Chandavalewadi School", village: "Chandaylewadi", taluka: "Uran", district: "Raigad", state: "Maharashtra" },
  { id: "s-342", school_name: "RZP Chirnerwadi School", village: "Chirnerwadi", taluka: "Uran", district: "Raigad", state: "Maharashtra" },
  { id: "s-343", school_name: "RZP School Gavthan", village: "Gavthan", taluka: "Uran", district: "Raigad", state: "Maharashtra" },
  { id: "s-344", school_name: "RZP Primary School Jambhulpada", village: "Jambhulpada", taluka: "Uran", district: "Raigad", state: "Maharashtra" },
  { id: "s-345", school_name: "RZP School Khoproliwadi", village: "Khoproliwadi", taluka: "Uran", district: "Raigad", state: "Maharashtra" },
  { id: "s-346", school_name: "RZP School Punadewadi", village: "Punadewadi", taluka: "Uran", district: "Raigad", state: "Maharashtra" },
  { id: "s-347", school_name: "RZP School Veshwiwadi", village: "Veshwiwadi", taluka: "Uran", district: "Raigad", state: "Maharashtra" },
  { id: "s-348", school_name: "Nanasaheb Dharmadhikari School Girls", village: "Uran", taluka: "Uran", district: "Raigad", state: "Maharashtra" },
  { id: "s-349", school_name: "RZP School Mulekhand", village: "Mulekhand", taluka: "Uran", district: "Raigad", state: "Maharashtra" },
  { id: "s-350", school_name: "RZP School Nagaon", village: "Nagaon", taluka: "Uran", district: "Raigad", state: "Maharashtra" },
  { id: "s-351", school_name: "RZP School Navin Sheva", village: "Navin Sheva", taluka: "Uran", district: "Raigad", state: "Maharashtra" },
  { id: "s-352", school_name: "RZP School Sheve Koliwada", village: "Sheva Koliwada", taluka: "Uran", district: "Raigad", state: "Maharashtra" },
  { id: "s-353", school_name: "RZP School Daurnagar", village: "Daurnagar", taluka: "Uran", district: "Raigad", state: "Maharashtra" },
  { id: "s-354", school_name: "RZP School Kaladhonda", village: "Kaladhonda", taluka: "Uran", district: "Raigad", state: "Maharashtra" },
  { id: "s-355", school_name: "RZP School Kondhari", village: "Kondhari", taluka: "Uran", district: "Raigad", state: "Maharashtra" },
  { id: "s-356", school_name: "RZP School Ranwad", village: "Ranwad", taluka: "Uran", district: "Raigad", state: "Maharashtra" },
  { id: "s-357", school_name: "Dronagiri Highschool", village: "Uran/Dronagiri", taluka: "Uran", district: "Raigad", state: "Maharashtra" },
  { id: "s-358", school_name: "Mora Municipal School", village: "Mora", taluka: "Uran", district: "Raigad", state: "Maharashtra" },
  { id: "s-359", school_name: "Abhyudaynagar School", village: "Abhyudaynagar", taluka: "Mumbai", district: "Mumbai", state: "Maharashtra" },
  { id: "s-360", school_name: "Mangirdevi Anganwadi", village: "Mangirdevi", taluka: "Uran", district: "Raigad", state: "Maharashtra" },
  { id: "s-361", school_name: "Badamwadi Anganawadi", village: "Badaamwadi", taluka: "Uran", district: "Raigad", state: "Maharashtra" },
  { id: "s-362", school_name: "Chanje Dronagiri Anganwadi", village: "Chanje Dronagiri", taluka: "Uran", district: "Raigad", state: "Maharashtra" },
  { id: "s-363", school_name: "Z.P.School Wathar", village: "Wathar", taluka: "Karad", district: "Satara", state: "Maharashtra" },
  { id: "s-364", school_name: "Kulgaon School No.1 Belvali, Badlapur", village: "Kulgaon", taluka: "Shahapur", district: "Thane", state: "Maharashtra" },
  { id: "s-365", school_name: "Z.P.School Jangalwasti", village: "Jangalwasti", taluka: "Vaijapur", district: "Chh.Sambhajinagar", state: "Maharashtra" },
  { id: "s-366", school_name: "Z.P.School Wadebolhai", village: "Wadebolhai", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-367", school_name: "Z.P.School Markal", village: "Markal", taluka: "Khed", district: "Pune", state: "Maharashtra" },
  { id: "s-368", school_name: "Saint Hildas Girls School", village: "Swargate", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-369", school_name: "Z.P.School Ghotkulewadi", village: "Ghotkulewadi", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-370", school_name: "Haji Abdul Majid Leader Urdu Girls Primary School", village: "Nagpur City", taluka: "Nagpur", district: "Nagpur", state: "Maharashtra" },
  { id: "s-371", school_name: "G. M. Banatwala Primary School", village: "Nagpur City", taluka: "Nagpur", district: "Nagpur", state: "Maharashtra" },
  { id: "s-372", school_name: "Vivekanand Primary and Secondary School", village: "Nagpur City", taluka: "Nagpur", district: "Nagpur", state: "Maharashtra" },
  { id: "s-373", school_name: "Kapil Nagar Hindi Uchh Primary School", village: "Nagpur City", taluka: "Nagpur", district: "Nagpur", state: "Maharashtra" },
  { id: "s-374", school_name: "Nayapura Hindi Upper Primary School", village: "Nagpur City", taluka: "Nagpur", district: "Nagpur", state: "Maharashtra" },
  { id: "s-375", school_name: "Elaben Mehta Taldeo Mahabaleshwar", village: "Taldeo", taluka: "Mahabaleshwar", district: "Satara", state: "Maharashtra" },
  { id: "s-376", school_name: "Z.P.School Kalhat", village: "Kalhat", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-377", school_name: "Z.P.School Sate", village: "Sate", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-378", school_name: "Sevadham Aashram Malegaon", village: "Malegaon", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-379", school_name: "Z.P.School Rajapuri", village: "Rajapuri", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-380", school_name: "Kamla Neharu Hindi Vidyalaya", village: "PCMC", taluka: "PCMC", district: "Pune", state: "Maharashtra" },
  { id: "s-381", school_name: "Dyandeep Vidyalaya Nandwal", village: "Nandwal", taluka: "Shahapur", district: "Thane", state: "Maharashtra" },
  { id: "s-382", school_name: "Z.P. School Darakwadi", village: "Darakwadi", taluka: "Rajguru Nagar", district: "Pune", state: "Maharashtra" },
  { id: "s-383", school_name: "Zilla Parishad Primary School Kuravli", village: "Kuravli", taluka: "Phaltan", district: "Satara", state: "Maharashtra" },
  { id: "s-384", school_name: "Chinchwad Badhir Mook Vidyalay Pune", village: "Nigdi", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-385", school_name: "Sant Sai English High School", village: "Bhosari", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-386", school_name: "Yashwantrao Chavan Primary and Secondary School", village: "Dighi Bhosari", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-387", school_name: "Zilla Parishad Primary School Kankwadi", village: "Kankwadi", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-388", school_name: "Zilla Parishad Primary School Urse", village: "Urse", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-389", school_name: "Zilla Parishad Primary School Shindevasti", village: "Shindevasti", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-390", school_name: "Zilla Parishad Primary School Bhongavli", village: "Bhongavli", taluka: "Bhor", district: "Pune", state: "Maharashtra" },
  { id: "s-391", school_name: "Swargeeya Vithal Tupe Smart Learning EMSS", village: "Malwadi Hadapsar", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-392", school_name: "Zilla Parishad Primary School Adhale Khurd", village: "Adhale Khurd", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-393", school_name: "Zilla Parishad Primary School Adhale Budruk", village: "Adhale Budruk", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-394", school_name: "Zilla Parishad Primary School Doane", village: "Doane", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-395", school_name: "Zilla Parishad Primary School Divad", village: "Divad", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-396", school_name: "Zilla Parishad Primary School Ovale", village: "Ovale", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-397", school_name: "Ma.na.pa. School No. 1 (Boys)", village: "Lohagaon", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-398", school_name: "Ma.na.pa. School No. 2 (Girls)", village: "Lohagaon", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-399", school_name: "Zilla Parishad Primary School Shivane", village: "Shivane", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-400", school_name: "Jila Parishad Prathmik School, Gohre Budruk", village: "Gohre Budruk", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-401", school_name: "Jila Parishad Prathmik School Zalanwadi", village: "Zalanwadi", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-402", school_name: "Jila Parishad Prathmik School Donaje", village: "Donaje", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-403", school_name: "Jila Parishad School Khamgaon Maval", village: "Khamgaon Maval", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-404", school_name: "Jila Parishad Prathmik School Markal", village: "Markal", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-405", school_name: "Jila Parishad Prathmik School Perane", village: "Perane", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-406", school_name: "Jila Parishad Prathmik School Tulapur", village: "Tulapur", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-407", school_name: "Jila Parishad Prathmik School Parandwadi", village: "Parandwadi", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-408", school_name: "Jila Parishad Prathmik School Ozarde", village: "Ozarde", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-409", school_name: "Jila Parishad Prathmik School Kalhat", village: "Kalhat", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-410", school_name: "Jila Parishad Prathmik School Ghotkulewadi", village: "Ghotkulewadi", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-411", school_name: "Jila Parishad Prathmik School Bramhanwadi", village: "Bramhanwadi (Baur)", taluka: "Maval", district: "Pune", state: "Maharashtra" },
  { id: "s-412", school_name: "Jila Parishad Prathmik School Vaghapur", village: "Vaghapur", taluka: "Purandhar", district: "Pune", state: "Maharashtra" },
  { id: "s-413", school_name: "Jila Parishad Prathmik School Pargaon Memane", village: "Pargaon Memane", taluka: "Purandhar", district: "Pune", state: "Maharashtra" },
  { id: "s-414", school_name: "Jila Parishad Prathmik School Kutwalwadi", village: "Kutwalwadi", taluka: "Purandhar", district: "Pune", state: "Maharashtra" },
  { id: "s-415", school_name: "Jila Parishad Prathmik School Supe No. 1", village: "Supe", taluka: "Baramati", district: "Pune", state: "Maharashtra" },
  { id: "s-416", school_name: "Jila Parishad Prathmik School Supe No. 2", village: "Supe", taluka: "Baramati", district: "Pune", state: "Maharashtra" },
  { id: "s-417", school_name: "Jila Parishad Prathmik School Borkarwadi", village: "Borkarwadi", taluka: "Baramati", district: "Pune", state: "Maharashtra" },
  { id: "s-418", school_name: "Jila Parishad Prathmik School Zhirkhelwasti", village: "Zhirkhelwasti", taluka: "Mulshi", district: "Pune", state: "Maharashtra" },
];
