CREATE TABLE IF NOT EXISTS platform_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    student_name TEXT,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 10),
    review_text TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE platform_reviews ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public access" ON platform_reviews;
CREATE POLICY "Public access" ON platform_reviews FOR ALL USING (true);
