<<<<<<< HEAD
-- Create Schools Table
CREATE TABLE IF NOT EXISTS schools (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    school_name TEXT NOT NULL,
    district TEXT NOT NULL,
    taluka TEXT NOT NULL,
    state TEXT DEFAULT 'Maharashtra',
    cluster TEXT,
    block TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create Users Table
=======
-- Create Users Table if not exists
>>>>>>> f7736d02016ee28b07eba970d82001144bd49b4d
CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    age INTEGER,
    grade TEXT, 
    role TEXT DEFAULT 'student',
    city TEXT,
    school TEXT,
    school_id TEXT,
    mobile TEXT, 
    password TEXT, 
    "totalPoints" INTEGER DEFAULT 0,
    books_read INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ensure missing columns exist in users (if table was created earlier)
DO $$ 
BEGIN 
    BEGIN
        ALTER TABLE users ADD COLUMN grade TEXT;
    EXCEPTION WHEN duplicate_column THEN NULL;
    END;
    BEGIN
        ALTER TABLE users ADD COLUMN role TEXT DEFAULT 'student';
    EXCEPTION WHEN duplicate_column THEN NULL;
    END;
END $$;

-- Create Reading Sessions Table if not exists
CREATE TABLE IF NOT EXISTS reading_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id TEXT NOT NULL,
    book_title TEXT,
    user_id TEXT NOT NULL REFERENCES users(id),
    start_time TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE,
    duration_seconds INTEGER DEFAULT 0,
    pages_read INTEGER DEFAULT 0,
    points_earned INTEGER DEFAULT 0,
    completed BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ensure missing columns exist in reading_sessions (if table was created earlier)
DO $$ 
BEGIN 
    BEGIN
        ALTER TABLE reading_sessions ADD COLUMN points_earned INTEGER DEFAULT 0;
    EXCEPTION WHEN duplicate_column THEN NULL;
    END;
    BEGIN
        ALTER TABLE reading_sessions ADD COLUMN duration_seconds INTEGER DEFAULT 0;
    EXCEPTION WHEN duplicate_column THEN NULL;
    END;
    BEGIN
        ALTER TABLE reading_sessions ADD COLUMN pages_read INTEGER DEFAULT 0;
    EXCEPTION WHEN duplicate_column THEN NULL;
    END;
    BEGIN
        ALTER TABLE reading_sessions ADD COLUMN book_title TEXT;
    EXCEPTION WHEN duplicate_column THEN NULL;
    END;
END $$;

-- Remove restrictive foreign keys that block sync if meta-data is missing
-- These constraints are often too strict for rural/offline environments
ALTER TABLE reading_sessions DROP CONSTRAINT IF EXISTS reading_sessions_book_id_fkey;
ALTER TABLE reading_sessions DROP CONSTRAINT IF EXISTS reading_sessions_user_id_fkey;
ALTER TABLE reading_sessions DROP CONSTRAINT IF EXISTS reading_sessions_user_id_fkey1;
ALTER TABLE reading_sessions DROP CONSTRAINT IF EXISTS reading_sessions_book_id_fkey1;

-- Create Books Table (Shared Library)
CREATE TABLE IF NOT EXISTS books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    "fileId" TEXT,
    grade TEXT,
    pages INTEGER,
    "pdfUrl" TEXT,
    level TEXT,
    subject TEXT,
    language TEXT,
    "coverUrl" TEXT,
    grade_level TEXT, -- Used by analytics proxy
    questions JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(title, level, language, subject)
);

-- Ensure missing columns exist in books (if table was created earlier)
DO $$ 
BEGIN 
    BEGIN
        ALTER TABLE books ADD COLUMN questions JSONB DEFAULT '[]'::jsonb;
    EXCEPTION WHEN duplicate_column THEN NULL;
    END;
    BEGIN
        ALTER TABLE books ADD COLUMN avg_rating FLOAT DEFAULT 0;
    EXCEPTION WHEN duplicate_column THEN NULL;
    END;
    BEGIN
        ALTER TABLE books ADD COLUMN review_count INTEGER DEFAULT 0;
    EXCEPTION WHEN duplicate_column THEN NULL;
    END;
END $$;

-- Create Schools Table (for analytics)
CREATE TABLE IF NOT EXISTS schools (
    id TEXT PRIMARY KEY,
    school_name TEXT NOT NULL,
    district TEXT,
    taluka TEXT,
    state TEXT,
    cluster TEXT,
    block TEXT
);

-- Analytics Views
-- 1. Student Reading Aggregations
DROP VIEW IF EXISTS analytics_student_books;
CREATE OR REPLACE VIEW analytics_student_books AS
SELECT 
    user_id,
    u.name as student_name,
    u.school_id,
    u.grade,
    COUNT(DISTINCT book_id) as total_books_read,
    SUM(duration_seconds) as total_reading_time_seconds,
    SUM(pages_read) as total_pages_read
FROM reading_sessions rs
JOIN users u ON rs.user_id = u.id
GROUP BY user_id, u.name, u.school_id, u.grade;

-- 2. Top Books/Levels
DROP VIEW IF EXISTS analytics_top_books;
CREATE OR REPLACE VIEW analytics_top_books AS
SELECT 
    rs.book_id,
    rs.book_title,
    b.grade_level,
    COUNT(*) as session_count
FROM reading_sessions rs
LEFT JOIN books b ON rs.book_id::text = b.id::text
GROUP BY rs.book_id, rs.book_title, b.grade_level;

-- 3. School Stats
DROP VIEW IF EXISTS analytics_school_stats;
CREATE OR REPLACE VIEW analytics_school_stats AS
SELECT 
    u.school_id,
    s.school_name,
    s.district,
    s.taluka,
    COUNT(*) as total_sessions,
    COUNT(DISTINCT rs.book_id) as unique_books_read,
    COUNT(DISTINCT rs.user_id) as participating_students
FROM reading_sessions rs
JOIN users u ON rs.user_id = u.id
JOIN schools s ON u.school_id = s.id
GROUP BY u.school_id, s.school_name, s.district, s.taluka;

-- Enable Row Level Security (RLS)
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE reading_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE books ENABLE ROW LEVEL SECURITY;
ALTER TABLE schools ENABLE ROW LEVEL SECURITY;

-- Create Policies (Permissive for demo)
DROP POLICY IF EXISTS "Public access" ON users;
CREATE POLICY "Public access" ON users FOR ALL USING (true);

DROP POLICY IF EXISTS "Public access" ON reading_sessions;
CREATE POLICY "Public access" ON reading_sessions FOR ALL USING (true);

DROP POLICY IF EXISTS "Public access" ON books;
CREATE POLICY "Public access" ON books FOR ALL USING (true);

DROP POLICY IF EXISTS "Public access" ON schools;
CREATE POLICY "Public access" ON schools FOR ALL USING (true);

-- Note: Storage setup (buckets and RLS) should be done via the Supabase Dashboard 
-- if you encounter 'must be owner' errors. 
-- 1. Create a public bucket named 'books'.
-- 2. Add a policy to allow 'public' access for all operations if it's a demo.

-- Book Reviews System
CREATE TABLE IF NOT EXISTS book_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL REFERENCES users(id),
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 10),
    review_text TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(book_id, user_id)
);

ALTER TABLE book_reviews ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public access" ON book_reviews;
CREATE POLICY "Public access" ON book_reviews FOR ALL USING (true);

-- Auto-calc average ratings trigger
CREATE OR REPLACE FUNCTION update_book_rating()
RETURNS TRIGGER AS $$
DECLARE
    target_book_id BIGINT;
BEGIN
    IF TG_OP = 'DELETE' THEN
        target_book_id := OLD.book_id;
    ELSE
        target_book_id := NEW.book_id;
    END IF;

    UPDATE books
    SET 
        avg_rating = (
            SELECT COALESCE(AVG(rating), 0)
            FROM book_reviews
            WHERE book_id = target_book_id
        ),
        review_count = (
            SELECT COUNT(*)
            FROM book_reviews
            WHERE book_id = target_book_id
        )
    WHERE id = target_book_id;
    
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    ELSE
        RETURN NEW;
    END IF;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_book_rating ON book_reviews;
CREATE TRIGGER trigger_update_book_rating
AFTER INSERT OR UPDATE OR DELETE ON book_reviews
FOR EACH ROW
EXECUTE FUNCTION update_book_rating();
