-- Create Users Table
CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    age INTEGER,
    city TEXT,
    school TEXT,
    mobile TEXT, -- Added mobile number
    password TEXT, -- Note: In a real app, use Supabase Auth. This is for the demo to match Dexie.
    "totalPoints" INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create Readings Table
CREATE TABLE IF NOT EXISTS readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "bookId" TEXT NOT NULL,
    "userId" TEXT NOT NULL REFERENCES users(id),
    "startTime" BIGINT NOT NULL,
    "endTime" BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create Books Table (Shared Library)
CREATE TABLE IF NOT EXISTS books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    "fileId" TEXT,
    grade TEXT,
    pages INTEGER,
    "pdfUrl" TEXT,
    level TEXT,
    subject TEXT,
    language TEXT,
    "coverUrl" TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(title, level, language, subject)
);

-- Ensure Composite Uniqueness (runs safely if already exists)
DO $$ 
BEGIN 
    -- Drop old title-only constraint if it exists
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'books_title_key') THEN
        ALTER TABLE books DROP CONSTRAINT books_title_key;
    END IF;
END $$;

-- Enable Row Level Security (RLS)
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE readings ENABLE ROW LEVEL SECURITY;
ALTER TABLE books ENABLE ROW LEVEL SECURITY;

-- Create Policies
DROP POLICY IF EXISTS "Public users access" ON users;
CREATE POLICY "Public users access" ON users FOR ALL USING (true);

DROP POLICY IF EXISTS "Public readings access" ON readings;
CREATE POLICY "Public readings access" ON readings FOR ALL USING (true);

DROP POLICY IF EXISTS "Public books access" ON books;
CREATE POLICY "Public books access" ON books FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin books management" ON books;
CREATE POLICY "Admin books management" ON books FOR ALL USING (true); -- Simplified for admin demo

-- Storage Infrastructure Setup
-- 1. Create the bucket if it doesn't exist
INSERT INTO storage.buckets (id, name, public)
VALUES ('books', 'books', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- 2. Enable RLS (Should be enabled by default on storage.objects, but ensuring here)
ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;

-- 3. Create permissive policies for the "books" bucket
-- Note: These policies allow ANY client with your API key to upload to this specific bucket.
DROP POLICY IF EXISTS "Allow Public Upload" ON storage.objects;
CREATE POLICY "Allow Public Upload" ON storage.objects 
FOR INSERT TO anon, authenticated 
WITH CHECK (bucket_id = 'books');

DROP POLICY IF EXISTS "Allow Public Update" ON storage.objects;
CREATE POLICY "Allow Public Update" ON storage.objects 
FOR UPDATE TO anon, authenticated 
USING (bucket_id = 'books') 
WITH CHECK (bucket_id = 'books');

DROP POLICY IF EXISTS "Allow Public Read" ON storage.objects;
CREATE POLICY "Allow Public Read" ON storage.objects 
FOR SELECT TO anon, authenticated 
USING (bucket_id = 'books');

DROP POLICY IF EXISTS "Allow Public Delete" ON storage.objects;
CREATE POLICY "Allow Public Delete" ON storage.objects 
FOR DELETE TO anon, authenticated 
USING (bucket_id = 'books');
