import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

declare const self: (ServiceWorkerGlobalScope & { __WB_MANIFEST: any[] }) | any;

self.skipWaiting();
clientsClaim();

// Precache all assets generated by the build (JS chunks, CSS, icons, cmaps, etc.)
precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();

// ── Runtime caching ─────────────────────────────────────────────────────────

// Page HTML: cache all same-origin non-API pages so dashboard/leaderboard/login
// load from cache when offline (after first online visit).
registerRoute(
    ({ url, sameOrigin }) => sameOrigin && !url.pathname.startsWith('/api/'),
    new NetworkFirst({
        cacheName: 'pages',
        networkTimeoutSeconds: 5,
        plugins: [
            new ExpirationPlugin({ maxEntries: 32, maxAgeSeconds: 24 * 60 * 60 }),
            new CacheableResponsePlugin({ statuses: [0, 200] }),
        ],
    })
);

// Next.js RSC / data payloads for client-side navigation
registerRoute(
    ({ url }) => url.pathname.startsWith('/_next/data/'),
    new NetworkFirst({
        cacheName: 'next-data',
        networkTimeoutSeconds: 5,
        plugins: [new ExpirationPlugin({ maxEntries: 32, maxAgeSeconds: 24 * 60 * 60 })],
    })
);

// Static Next.js assets — content-hashed, safe to cache forever
registerRoute(
    ({ url }) => url.pathname.startsWith('/_next/static/'),
    new CacheFirst({
        cacheName: 'next-static-js-assets',
        plugins: [new ExpirationPlugin({ maxEntries: 128, maxAgeSeconds: 365 * 24 * 60 * 60 })],
    })
);

// Next.js image optimisation
registerRoute(
    ({ url }) => url.pathname.startsWith('/_next/image'),
    new StaleWhileRevalidate({
        cacheName: 'next-image',
        plugins: [new ExpirationPlugin({ maxEntries: 64, maxAgeSeconds: 24 * 60 * 60 })],
    })
);

// Static public images (avatars, icons, logos)
registerRoute(
    ({ url }) => /\.(png|jpg|jpeg|gif|svg|webp|ico)$/i.test(url.pathname),
    new CacheFirst({
        cacheName: 'static-image-assets',
        plugins: [
            new ExpirationPlugin({ maxEntries: 64, maxAgeSeconds: 30 * 24 * 60 * 60 }),
            new CacheableResponsePlugin({ statuses: [0, 200] }),
        ],
    })
);

// Supabase API — NetworkFirst so data stays fresh, falls back to cache offline
registerRoute(
    ({ url }) => url.hostname.includes('.supabase.co'),
    new NetworkFirst({
        cacheName: 'supabase-cache',
        networkTimeoutSeconds: 10,
        plugins: [new CacheableResponsePlugin({ statuses: [0, 200] })],
    })
);
