-- BULK INSERT ALL SCHOOLS
-- Run this in Supabase SQL Editor

-- 1. Ensure columns exist
ALTER TABLE schools 
  ADD COLUMN IF NOT EXISTS village TEXT,
  ADD COLUMN IF NOT EXISTS state TEXT DEFAULT 'Maharashtra',
  ADD COLUMN IF NOT EXISTS cluster TEXT,
  ADD COLUMN IF NOT EXISTS block TEXT;

-- 2. Insert the data
INSERT INTO schools (id, school_name, village, taluka, district, state)
VALUES
  ('s-1', 'Community center', 'Surangali', 'Bhokardhan', 'Jalna', 'Maharashtra'),
  ('s-2', 'G.S Choudhari School', 'Varangaon', 'Bhusawal', 'Jalgaon', 'Maharashtra'),
  ('s-3', 'Z.P. School Vangani', 'Vangani', 'Ambernath', 'Thane', 'Maharashtra'),
  ('s-4', 'Z.P.School Chikatgaon', 'Chikatgaon', 'Vaijapur', 'Chh.Sambhajinagar', 'Maharashtra'),
  ('s-5', 'Z.P.School Chorwaghalgaon', 'Chorwaghalgaon', 'Vaijapur', 'Chh.Sambhajinagar', 'Maharashtra'),
  ('s-6', 'Z.P School, Badakwasti', 'Palshi', 'Sillod', 'Chh.Sambhajinagar', 'Maharashtra'),
  ('s-7', 'Balpan School, Panodi', 'Panodi', 'Sangamner', 'Ahmednagar', 'Maharashtra'),
  ('s-8', 'Z.P.School Kalegaon', 'Kalegaon', 'Khamgaon', 'Buldhana', 'Maharashtra'),
  ('s-9', 'Z.P School, Kumbefal', 'Kumbefal', 'Khamgaon', 'Buldhana', 'Maharashtra'),
  ('s-10', 'Z.P School, Antradneed, Neral', 'Antrad Need', 'Karjat', 'Raigad', 'Maharashtra'),
  ('s-11', 'Z.P School, Aswalamba', 'Aswalamba', 'Parli', 'Beed', 'Maharashtra'),
  ('s-12', 'Z.P School, Samrala', 'Samrala', 'Dharmabad', 'Nanded', 'Maharashtra'),
  ('s-13', 'Z.P School, Rumhana', 'Rumhana', 'Sindhkhedraja', 'Buldhana', 'Maharashtra'),
  ('s-14', 'Z.P School, Gajanan Nagar', 'Nillod', 'Sillod', 'Chh.Sambhajinagar', 'Maharashtra'),
  ('s-15', 'Z.P School, Mahalgaon', 'Mahalgaon', 'Vaijapur', 'Chh.Sambhajinagar', 'Maharashtra'),
  ('s-16', 'Z.P School, Poshir', 'Poshir', 'Karjat', 'Raigad', 'Maharashtra'),
  ('s-17', 'Z.P School, Kalyachi Wadi', 'Kalyachi Wadi', 'Karjat', 'Raigad', 'Maharashtra'),
  ('s-18', 'Z.P School, Devlipada', 'Devlipada', 'Shahapur', 'Thane', 'Maharashtra'),
  ('s-19', 'Z.P School, Pashtepada', 'Pashtepada', 'Shahapur', 'Thane', 'Maharashtra'),
  ('s-20', 'Z.P School, Gohre Budruk', 'Gohre Budruk', 'Haveli', 'Pune', 'Maharashtra'),
  ('s-21', 'Z.P School Mandwa', 'Mandwa', 'Parli', 'Beed', 'Maharashtra'),
  ('s-22', 'Adarsh Vidyalya, Mandwa', 'Mandwa', 'Parli', 'Beed', 'Maharashtra'),
  ('s-23', 'Z.P School Mirwat', 'Mirwat', 'Parli', 'Beed', 'Maharashtra'),
  ('s-24', 'Z.P School, Kasarwadi', 'Kasarwadi', 'Parli', 'Beed', 'Maharashtra'),
  ('s-25', 'Sant.Janabai Vidyalya, Gangakhed', 'Gangakhed', 'Gangakhed', 'Parbhani', 'Maharashtra'),
  ('s-26', 'Z.P School, Ambivali', 'Ambivali', 'Karjat', 'Raigad', 'Maharashtra'),
  ('s-27', 'Z.P.School, Palaskheda Murtad', 'Palaskheda Murtad', 'Bhokardhan', 'Jalna', 'Maharashtra'),
  ('s-28', 'Z.P.School Zavkheda Thombre', 'Zavkheda Thombre', 'Bhokardhan', 'Jalna', 'Maharashtra'),
  ('s-29', 'Z.P School, Indapwadi', 'Indapwadi', 'Parli', 'Beed', 'Maharashtra'),
  ('s-30', 'Z.P School, Chandai Khurd', 'Chandai Khurd', 'Karjat', 'Raigad', 'Maharashtra'),
  ('s-31', 'Z.P.School, Mamdapur', 'Mamdapur', 'Parli', 'Beed', 'Maharashtra'),
  ('s-32', 'Ashram Shala, Kaudgaon Huda', 'Kaudgaon Ghoda', 'Parli', 'Beed', 'Maharashtra'),
  ('s-33', 'Z.P School, Jambergaon', 'Jambergaon', 'Vaijapur', 'Chh.Sambhajinagar', 'Maharashtra'),
  ('s-34', 'Z.P. School, Sayala', 'Sayala', 'Palam', 'Parbhani', 'Maharashtra'),
  ('s-35', 'Z.P. School, Bastwad', 'Bastwad', 'Shirol', 'Kolhapur', 'Maharashtra'),
  ('s-36', 'Z.P. School, Majrewadi', 'Majrewadi', 'Shirol', 'Kolhapur', 'Maharashtra'),
  ('s-37', 'Z.P. School, Rajapurwadi', 'Rajapurwadi', 'Shirol', 'Kolhapur', 'Maharashtra'),
  ('s-38', 'Z.P. School, Antrat Varedi', 'Antrat Varedi', 'Karjat', 'Raigad', 'Maharashtra'),
  ('s-39', 'Z.P. School, Lakhanwada', 'Lakhanwada', 'Khamgaon', 'Buldhana', 'Maharashtra'),
  ('s-40', 'Z.P. School, Bothakazi', 'Bothakazi', 'Khamgaon', 'Buldhana', 'Maharashtra'),
  ('s-41', 'Z.P. School Malisagaj', 'Malisagaj', 'Vaijapur', 'Chh.Sambhajinagar', 'Maharashtra'),
  ('s-42', 'Z.P. School Bhagur', 'Bhagur', 'Vaijapur', 'Chh.Sambhajinagar', 'Maharashtra'),
  ('s-43', 'Z.P School, Malyan, Dahanu', 'Malyan', 'Dahanu', 'Palghar', 'Maharashtra'),
  ('s-44', 'Z.P School Vadkun Dandipada', 'Vadkun Dandipada', 'Dahanu', 'Palghar', 'Maharashtra'),
  ('s-45', 'Z.P.School, Narpad', 'Narpad', 'Dahanu', 'Palghar', 'Maharashtra'),
  ('s-46', 'Z.P School Badapokhran', 'Badapokhran', 'Dahanu', 'Palghar', 'Maharashtra'),
  ('s-47', 'Z.P School Varor', 'Pavalepada, Varor', 'Dahanu', 'Palghar', 'Maharashtra'),
  ('s-48', 'Z.P Girls School, Satpati', 'Satpati', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-49', 'Z.P School Urdu, Satpati', 'Satpati', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-50', 'Z.P School, Satpati', 'Satpati', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-51', 'Z.P.School Vadrai', 'Vadrai', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-52', 'Z.P. School, Devpada', 'Devpada', 'Karjat', 'Raigad', 'Maharashtra'),
  ('s-53', 'Z.P School, Eknathwadi', 'Eknathwadi', 'Karjat', 'Raigad', 'Maharashtra'),
  ('s-54', 'Prithviraj Kapoor Highschool', 'Lonikalbhor', 'Haveli', 'Pune', 'Maharashtra'),
  ('s-55', 'R.Z.P. School Mandave', 'Mandve', 'Alibag', 'Raigad', 'Maharashtra'),
  ('s-56', 'Z.School Zalanwadi', 'Zalanwadi', 'Haveli', 'Pune', 'Maharashtra'),
  ('s-57', 'Shakuntalabai Shitole School', 'Sangvi', 'Haveli', 'Pune', 'Maharashtra'),
  ('s-58', 'R.Z.P. School, Wakas', 'Wakas', 'Karjat', 'Raigad', 'Maharashtra'),
  ('s-59', 'R.Z.P.School Newali', 'Newali', 'Karjat', 'Raigad', 'Maharashtra'),
  ('s-60', 'Z.P School, Chinchwad Goan', 'Chinchwadgoan', 'Vaijapur', 'Chh.Sambhajinagar', 'Maharashtra'),
  ('s-61', 'Patit Pawan Vidhyamandir, Ozarde', 'Ozarde', 'Wai', 'Satara', 'Maharashtra'),
  ('s-62', 'Z.P. School Aadhe', 'Aadhe', 'Haveli', 'Pune', 'Maharashtra'),
  ('s-63', 'Z.P. School, Vadu Khurd', 'Vadu Khurd', 'Haveli', 'Pune', 'Maharashtra'),
  ('s-64', 'Z.P School, Nadhi', 'Nadhi', 'Vaijapur', 'Chh.Sambhajinagar', 'Maharashtra'),
  ('s-65', 'Z.P. School, AgarSaigoan', 'Agarsaigoan', 'Vaijapur', 'Chh.Sambhajinagar', 'Maharashtra'),
  ('s-66', 'Z.P.School Bakori', 'Bakori', 'Haveli', 'Pune', 'Maharashtra'),
  ('s-67', 'Z.P. School Lonikalbhor', 'Lonikalbhor', 'Haveli', 'Pune', 'Maharashtra'),
  ('s-68', 'Pareshwar Vidhyalay, Pargoan Memane', 'Pargoan Memane', 'Purandhar', 'Pune', 'Maharashtra'),
  ('s-69', 'Z.P.School Lonikand', 'Lonikand', 'Haveli', 'Pune', 'Maharashtra'),
  ('s-70', 'Madh Municipal School', 'Madh Beach', 'Malad', 'Mumbai', 'Maharashtra'),
  ('s-71', 'Erangal Municipal School', 'Erangal Beach', 'Malad', 'Mumbai', 'Maharashtra'),
  ('s-72', 'Gorai Municipal School', 'Gorai Beach', 'Malad', 'Mumbai', 'Maharashtra'),
  ('s-73', 'Z.P. School Arnala Fort', 'Arnala Killa', 'Vasai', 'Palghar', 'Maharashtra'),
  ('s-74', 'Z.P.School Arnala Village', 'Arnala', 'Vasai', 'Palghar', 'Maharashtra'),
  ('s-75', 'Z.P. School Edwan', 'Edwan', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-76', 'Z.P. School Mahim Gavrai', 'Mahim', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-77', 'Z.P.School Mahim Tembhi', 'Mahim Tembhi', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-78', 'Z.P.School Kharekuran', 'Kharekuran', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-79', 'Z.P. School, Uchheli', 'Uccheli', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-80', 'Z.P. School Dhakti Dahanu', 'Dhakti Dahanu', 'Dahanu', 'Palghar', 'Maharashtra'),
  ('s-81', 'Z.P. School, Dahanu No.2', 'Dahanu No 2', 'Dahanu', 'Palghar', 'Maharashtra'),
  ('s-82', 'Z.P. School, Dahanu Agar', 'Dahanu Agar', 'Dahanu', 'Palghar', 'Maharashtra'),
  ('s-83', 'Z.P.School Malwandi Dhore', 'Malvandi', 'Haveli', 'Pune', 'Maharashtra'),
  ('s-84', 'Z.P. School Sadavli', 'Sadavli', 'Haveli', 'Pune', 'Maharashtra'),
  ('s-85', 'Z.P.School Ozarde', 'Ozarde', 'Haveli', 'Pune', 'Maharashtra'),
  ('s-86', 'Z.P.School Mhaskewasti Shivane', 'Shivane', 'Haveli', 'Pune', 'Maharashtra'),
  ('s-87', 'Z.P.School Kankwadi', 'Kankwadi', 'Haveli', 'Pune', 'Maharashtra'),
  ('s-88', 'Z.P.School Shivne', 'Shivane', 'Haveli', 'Pune', 'Maharashtra'),
  ('s-89', 'Z.P.School Bramhanwadi', 'Bramhanwadi (Baur)', 'Haveli', 'Pune', 'Maharashtra'),
  ('s-90', 'Z.P. School Baur', 'Baur', 'Haveli', 'Pune', 'Maharashtra'),
  ('s-91', 'Z.P.School Thugaon', 'Thugaon', 'Haveli', 'Pune', 'Maharashtra'),
  ('s-92', 'Z.P.School Chandkhed', 'Chandkhed', 'Haveli', 'Pune', 'Maharashtra'),
  ('s-93', 'Z.P.School Dhamani', 'Dhamne', 'Haveli', 'Pune', 'Maharashtra'),
  ('s-94', 'Z.P.School Urse', 'Urse', 'Haveli', 'Pune', 'Maharashtra'),
  ('s-95', 'Z.P.School Parandwadi', 'Parandwadi', 'Haveli', 'Pune', 'Maharashtra'),
  ('s-96', 'Z.P.School Ghaigaon', 'Ghaigaon', 'Vaijapur', 'Chh.Sambhajinagar', 'Maharashtra'),
  ('s-97', 'Netaji Subhash Vidyalay Pathri', 'Pathri', 'Pathri', 'Parbhani', 'Maharashtra'),
  ('s-98', 'Z.P.School Posari', 'Posari', 'Karjat', 'Raigad', 'Maharashtra'),
  ('s-99', 'Z.P. School Koliwali', 'Koliwali', 'Karjat', 'Raigad', 'Maharashtra'),
  ('s-100', 'R.Z.P.School Pimploli', 'Pimploli', 'Karjat', 'Raigad', 'Maharashtra'),
  ('s-101', 'Z.P.School Jagadambanagar', 'Jagdambanagar', 'Omerga', 'Dharashiv', 'Maharashtra'),
  ('s-102', 'Z.P.School Bet Jawalga', 'Jawalga', 'Omerga', 'Dharashiv', 'Maharashtra'),
  ('s-103', 'Z.P.School Dalimb', 'Dalimb', 'Omerga', 'Dharashiv', 'Maharashtra'),
  ('s-104', 'Z.P.School Yeli', 'Yeli', 'Omerga', 'Dharashiv', 'Maharashtra'),
  ('s-105', 'Z.P.School Samudral', 'Samudral', 'Omerga', 'Dharashiv', 'Maharashtra'),
  ('s-106', 'Sanskar Vidhyapeeth, Ramzanwadi', 'Ramjanwadi', 'Vapi', 'Valsad', 'Gujarat'),
  ('s-107', 'Govt School Salvav', 'Salvav', 'Vapi', 'Valsad', 'Gujarat'),
  ('s-108', 'Bhavnaben Naginbhai Patel School', 'Salvav Koliwad', 'Vapi', 'Valsad', 'Gujarat'),
  ('s-109', 'Govt School Azadnagar', 'Azadnagar', 'Vapi', 'Valsad', 'Gujarat'),
  ('s-110', 'Nagar Parishad School Karad', 'Karad', 'Karad', 'Satara', 'Maharashtra'),
  ('s-111', 'Z.P. School Devrashtre', 'Devrashtre', 'Sangli', 'Satara', 'Maharashtra'),
  ('s-112', 'Z.P. School, Temgharwadi', 'Temgharwadi', 'Khed', 'Pune', 'Maharashtra'),
  ('s-113', 'Z.P. School, Waki', 'Waki', 'Khed', 'Pune', 'Maharashtra'),
  ('s-114', 'Z.P.School Ladwad', 'Ladwad', 'Khed', 'Pune', 'Maharashtra'),
  ('s-115', 'Z.P.School Gargoti Shiwar', 'Gargoti Shivar', 'Khed', 'Pune', 'Maharashtra'),
  ('s-116', 'Asram Shala Wada', 'Wada', 'Wada', 'Palghar', 'Maharashtra'),
  ('s-117', 'Z.P.School Khondoshi', 'Kondoshi', 'Bhudargad', 'Kolhapur', 'Maharashtra'),
  ('s-118', 'Z.P. School Bhakaricha Pada', 'Bhakaricha Pada', 'Karjat', 'Raigad', 'Maharashtra'),
  ('s-119', 'Z.P.School Pethsangavi', 'Peth Sangavi', 'Omerga', 'Dharashiv', 'Maharashtra'),
  ('s-120', 'Z.P.School Mahalingraiwadi', 'Mahalingraiwadi', 'Omerga', 'Dharashiv', 'Maharashtra'),
  ('s-121', 'Z.P. School Tugaon', 'Ujani', 'Omerga', 'Dharashiv', 'Maharashtra'),
  ('s-122', 'Z.P.School Ukadgaon', 'Ukadgaon', 'Sonpeth', 'Parbhani', 'Maharashtra'),
  ('s-123', 'Z.P.School Dagadewadi', 'Dagadewadi', 'Parali', 'Beed', 'Maharashtra'),
  ('s-124', 'Dyanbodhini Primary School', 'Parali Vaijanath', 'Parali', 'Beed', 'Maharashtra'),
  ('s-125', 'Aadarshya Vidhyalay Mandva', 'Mandva', 'Parali', 'Beed', 'Maharashtra'),
  ('s-126', 'Z.P. School Vasahat, Dadahari Vadgaon', 'Vasahat Vadgaon', 'Parali', 'Beed', 'Maharashtra'),
  ('s-127', 'Z.P. School Zari', 'Zari', 'Pathri', 'Parbhani', 'Maharashtra'),
  ('s-128', 'Z.P.School Waghala', 'Waghala', 'Pathri', 'Parbhani', 'Maharashtra'),
  ('s-129', 'Z.P. School Babultar', 'Babultar', 'Pathri', 'Parbhani', 'Maharashtra'),
  ('s-130', 'Z.P.School Kutwalwadi', 'Kutwalwadi', 'Baramati', 'Pune', 'Maharashtra'),
  ('s-131', 'Z.P. School, Kotbi-Bujadpada', 'Chari-Kotbi', 'Dahanu', 'Palghar', 'Maharashtra'),
  ('s-132', 'Z.P. School Chikhle', 'Chikhle', 'Dahanu', 'Palghar', 'Maharashtra'),
  ('s-133', 'Z.P. School Vadakati', 'Vadaktipada', 'Dahanu', 'Palghar', 'Maharashtra'),
  ('s-134', 'Z.P. School Dhumket', 'Dhumket', 'Dahanu', 'Palghar', 'Maharashtra'),
  ('s-135', 'Z.P.School Kharlepada', 'Kharlepada', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-136', 'Z.P. School Manpada', 'Manpada', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-137', 'Z.P. School Vikasnagar', 'Vikas Nagar', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-138', 'Z.P. School, Shegatpada Satpati', 'Satpati', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-139', 'Urdu School Satpati', 'Satpati', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-140', 'Shaskiya Matsavyavsay Pri School Satpati', 'Satpati', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-141', 'Shaskiya Madhyamik Shala Satpati', 'Satpati', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-142', 'Z.P. School Popharan Dandi', 'Popharan Dandi', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-143', 'Z.P. School Tembi', 'Tembhi', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-144', 'Z.P. School Pam', 'Pam', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-145', 'Z.P. School, Murbe', 'Murbe', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-146', 'Z.P. School Navapur', 'Navapur', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-147', 'Z.P. School Ambedkar Nagar', 'Ambedkar Nagar', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-148', 'Z.P. School, Ghivali', 'Ghivali', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-149', 'Z.P.School Chikhal Dongare', 'Chikhal Dongari', 'Vasai', 'Palghar', 'Maharashtra'),
  ('s-150', 'Z.P. School Kasrali', 'Kasrali', 'Vasai', 'Palghar', 'Maharashtra'),
  ('s-151', 'Z.P. School Dahisar', 'Dahisar', 'Vasai', 'Palghar', 'Maharashtra'),
  ('s-152', 'Z.P. School Mazgaon', 'Mazgaon', 'Murud', 'Raigad', 'Maharashtra'),
  ('s-153', 'R.Z.P.School Nandgaon No.3', 'Nandgaon', 'Murud', 'Raigad', 'Maharashtra'),
  ('s-154', 'R.Z.P.School Nandgaon No.1', 'Nandgaon', 'Murud', 'Raigad', 'Maharashtra'),
  ('s-155', 'R.Z.P.School Aadad', 'Adad', 'Murud', 'Raigad', 'Maharashtra'),
  ('s-156', 'R.Z.P.School Bhoste', 'Bhoste', 'Shrivardhan', 'Raigad', 'Maharashtra'),
  ('s-157', 'R.Z.P.School Jaswali Marathi', 'Jasavli', 'Shrivardhan', 'Raigad', 'Maharashtra'),
  ('s-158', 'R.Z.P.School Urdu Arathi', 'Arathi', 'Shrivardhan', 'Raigad', 'Maharashtra'),
  ('s-159', 'R.Z.P.School Nhave', 'Nhave', 'Panvel', 'Raigad', 'Maharashtra'),
  ('s-160', 'R.Z.P. School & Primary School Nhave Khadi', 'Nhave Khadi', 'Panvel', 'Raigad', 'Maharashtra'),
  ('s-161', 'Z.P. School Kevale', 'Kevale', 'Panvel', 'Raigad', 'Maharashtra'),
  ('s-162', 'Z.P. School Shivkar', 'Shivkar', 'Panvel', 'Raigad', 'Maharashtra'),
  ('s-163', 'Z.P. School Kalundre', 'Kalundre', 'Panvel', 'Raigad', 'Maharashtra'),
  ('s-164', 'Kendriya Vidhyalay, Panvel', 'ONGC Colony', 'Panvel', 'Raigad', 'Maharashtra'),
  ('s-165', 'Z.P. School Deshmukh Takali', 'Deshmukh', 'Parali', 'Beed', 'Maharashtra'),
  ('s-166', 'Z.P.School Aaswalamba Tanda', 'Aswalamba Tanda', 'Parali', 'Beed', 'Maharashtra'),
  ('s-167', 'Z.P.School Wadgaon Dadhari', 'Wadgaon Dadahari', 'Parli', 'Beed', 'Maharashtra'),
  ('s-168', 'Z.P.School Dharmapuri', 'Dharmapuri', 'Parali', 'Beed', 'Maharashtra'),
  ('s-169', 'Z.P. School Pimpri Bk', 'Pimpri Bk', 'Parali', 'Beed', 'Maharashtra'),
  ('s-170', 'Z.P. School Panshet', 'Panshet', 'Haveli', 'Pune', 'Maharashtra'),
  ('s-171', 'Z.P. School Nanegaon', 'Nanegaon', 'Paithan', 'Chh.Sambhajinagar', 'Maharashtra'),
  ('s-172', 'Z.P.School Pashta', 'Pashta', 'Jalna', 'Jalna', 'Maharashtra'),
  ('s-173', 'Z.P.School Malnathpur', 'Malnathpur', 'Parali', 'Beed', 'Maharashtra'),
  ('s-174', 'Z.P. School Perne', 'Perne', 'Haveli', 'Pune', 'Maharashtra'),
  ('s-175', 'Kai. Lala Patil Phad Highschool Ghatsawali', 'Ghatsawali', 'Beed', 'Beed', 'Maharashtra'),
  ('s-176', 'Z.P. School Pargaon Memane', 'Pargaon Memane', 'Purandhar', 'Pune', 'Maharashtra'),
  ('s-177', 'Panchakrishi Shetkari Vidhyalay, Waghapur', 'Waghapur', 'Purandhar', 'Pune', 'Maharashtra'),
  ('s-178', 'Z.P.School Malegaon', 'Malegaon', 'Haveli', 'Pune', 'Maharashtra'),
  ('s-179', 'Z.P.School Kajala', 'Kajala', 'Dharashiv', 'Dharashiv', 'Maharashtra'),
  ('s-180', 'Z.P.School Ghatangri', 'Ghatangri', 'Dharashiv', 'Dharashiv', 'Maharashtra'),
  ('s-181', 'Z.P.School Varuda', 'Varuda', 'Dharashiv', 'Dharashiv', 'Maharashtra'),
  ('s-182', 'Z.P.Girls School Kond', 'Kond', 'Dharashiv', 'Dharashiv', 'Maharashtra'),
  ('s-183', 'Z.P.School Tugaon', 'Tugaon', 'Dharashiv', 'Dharashiv', 'Maharashtra'),
  ('s-184', 'Z.P.School Kasai', 'Kasai', 'Tuljapur', 'Dharashiv', 'Maharashtra'),
  ('s-185', 'Z.P.School Pimpla Khurd', 'Pimpla Khurd', 'Tuljapur', 'Dharashiv', 'Maharashtra'),
  ('s-186', 'Z.P.School Sindgaon', 'Sindgaon', 'Tuljapur', 'Dharashiv', 'Maharashtra'),
  ('s-187', 'Z.P.School Yevti', 'Yevti', 'Tuljapur', 'Dharashiv', 'Maharashtra'),
  ('s-188', 'Z.P.School Keshgaon', 'Keshgaon', 'Tuljapur', 'Dharashiv', 'Maharashtra'),
  ('s-189', 'Z.P.School Peth Ter', 'Peth Ter', 'Dharashiv', 'Dharashiv', 'Maharashtra'),
  ('s-190', 'Z.P.School Aalni', 'Aalni', 'Dharashiv', 'Dharashiv', 'Maharashtra'),
  ('s-191', 'Z.P.School Takviki', 'Takviki', 'Dharashiv', 'Dharashiv', 'Maharashtra'),
  ('s-192', 'Z.P.School Karanjkheda', 'Karanjkheda', 'Dharashiv', 'Dharashiv', 'Maharashtra'),
  ('s-193', 'Z.P.School Nandurga', 'Nandurga', 'Dharashiv', 'Dharashiv', 'Maharashtra'),
  ('s-194', 'Z.P.School Kijal', 'Kijal', 'Tuljapur', 'Dharashiv', 'Maharashtra'),
  ('s-195', 'Z.P.School Raikhel', 'Raikhel', 'Tuljapur', 'Dharashiv', 'Maharashtra'),
  ('s-196', 'Z.P.School Khudawadi', 'Khudawadi', 'Tuljapur', 'Dharashiv', 'Maharashtra'),
  ('s-197', 'Z.P.School Raghuchiwadi', 'Raghuchiwadi', 'Dharashiv', 'Dharashiv', 'Maharashtra'),
  ('s-198', 'Z.P.School Devlali', 'Devlali', 'Dharashiv', 'Dharashiv', 'Maharashtra'),
  ('s-199', 'Z.P.School Kakramba', 'Kakramba', 'Tuljapur', 'Dharashiv', 'Maharashtra'),
  ('s-200', 'Z.P.School Khemwadi', 'Khemwadi', 'Tuljapur', 'Dharashiv', 'Maharashtra'),
  ('s-201', 'Z.P.School Nilegaon', 'Nilegaon', 'Tuljapur', 'Dharashiv', 'Maharashtra'),
  ('s-202', 'Z.P.School Horti', 'Horti', 'Tuljapur', 'Dharashiv', 'Maharashtra'),
  ('s-203', 'Z.P.School Jalkot', 'Jalkot', 'Tuljapur', 'Dharashiv', 'Maharashtra'),
  ('s-204', 'Z.P.School Manglur', 'Manglur', 'Kalamb', 'Dharashiv', 'Maharashtra'),
  ('s-205', 'Z.P.School Bhatshirpura', 'Bhatshirpura', 'Kalamb', 'Dharashiv', 'Maharashtra'),
  ('s-206', 'Z.P.School Babhalgaon', 'Babhalgaon', 'Kalamb', 'Dharashiv', 'Maharashtra'),
  ('s-207', 'Z.P.School Uplai', 'Uplai', 'Kalamb', 'Dharashiv', 'Maharashtra'),
  ('s-208', 'Z.P.School Pimpri Shirdhon', 'Pimpri Shirdhon', 'Kalamb', 'Dharashiv', 'Maharashtra'),
  ('s-209', 'Z.P.School Bavi', 'Bavi', 'Washi', 'Dharashiv', 'Maharashtra'),
  ('s-210', 'Z.P.Girls School Terkheda', 'Terkheda', 'Washi', 'Dharashiv', 'Maharashtra'),
  ('s-211', 'Z.P.School Kanheri', 'Kanheri', 'Washi', 'Dharashiv', 'Maharashtra'),
  ('s-212', 'Z.P.School Pimpalwadi', 'Pimpalwadi', 'Paranda', 'Dharashiv', 'Maharashtra'),
  ('s-213', 'Z.P.School Takali', 'Takali', 'Paranda', 'Dharashiv', 'Maharashtra'),
  ('s-214', 'Z.P.School Shirala', 'Shirala', 'Paranda', 'Dharashiv', 'Maharashtra'),
  ('s-215', 'Z.P.School Ghargaon', 'Ghargaon', 'Paranda', 'Dharashiv', 'Maharashtra'),
  ('s-216', 'Z.P.School Devgaon Budruk', 'Devgaon Budruk', 'Paranda', 'Dharashiv', 'Maharashtra'),
  ('s-217', 'Z.P.School Shelgaon', 'Shelgaon', 'Paranda', 'Dharashiv', 'Maharashtra'),
  ('s-218', 'Z.P.School Jewali (South)', 'Jewali (South)', 'Lohara', 'Dharashiv', 'Maharashtra'),
  ('s-219', 'Z.P.School Rajegaon', 'Rajegaon', 'Lohara', 'Dharashiv', 'Maharashtra'),
  ('s-220', 'Z.P.School Bhosga', 'Bhosga', 'Lohara', 'Dharashiv', 'Maharashtra'),
  ('s-221', 'Z.P.School Hipparga Rava', 'Hipparga Rava', 'Lohara', 'Dharashiv', 'Maharashtra'),
  ('s-222', 'Z.P.School Aarsoli', 'Aarsoli', 'Bhoom', 'Dharashiv', 'Maharashtra'),
  ('s-223', 'Z.P.School Walha', 'Walha', 'Bhoom', 'Dharashiv', 'Maharashtra'),
  ('s-224', 'Z.P.School Chincholi', 'Chincholi', 'Bhoom', 'Dharashiv', 'Maharashtra'),
  ('s-225', 'Z.P.School Tintraj', 'Tintraj', 'Bhoom', 'Dharashiv', 'Maharashtra'),
  ('s-226', 'Z.P.School Nipani', 'Nipani', 'Bhoom', 'Dharashiv', 'Maharashtra'),
  ('s-227', 'Z.P.School Trikoli', 'Trikoli', 'Omerga', 'Dharashiv', 'Maharashtra'),
  ('s-228', 'Z.P.School Belamb', 'Belamb', 'Omerga', 'Dharashiv', 'Maharashtra'),
  ('s-229', 'Z.P.School Koral', 'Koral', 'Omerga', 'Dharashiv', 'Maharashtra'),
  ('s-230', 'Z.P.School Aashta', 'Aashta', 'Omerga', 'Dharashiv', 'Maharashtra'),
  ('s-231', 'Z.P.School Balsur', 'Balsur', 'Omerga', 'Dharashiv', 'Maharashtra'),
  ('s-232', 'Mahatma Phule Vidyalay Khodad', 'Khodad', 'Junnar', 'Pune', 'Maharashtra'),
  ('s-233', 'Z.P.School Hanuman Nagar', 'Shigaon', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-234', 'Z.P.School Katkaripada', 'Haloli', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-235', 'Z.P.School Velgaon', 'Manor', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-236', 'Z.P.School Devulpada', 'Chahade', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-237', 'Z.P.School Chalani Tivaspada', 'Saiwan', 'Dahanu', 'Palghar', 'Maharashtra'),
  ('s-238', 'Z.P.School Mahalpada', 'Ganjad', 'Dahanu', 'Palghar', 'Maharashtra'),
  ('s-239', 'Z.P.School Vasantvadi', 'Vasantwadi', 'Dahanu', 'Palghar', 'Maharashtra'),
  ('s-240', 'Z.P.School Haloli - Padavalpada', 'Haloli', 'Dahanu', 'Palghar', 'Maharashtra'),
  ('s-241', 'Z.P.School Kirat', 'Kirat', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-242', 'Z.P.School Haloli Gavthanpada', 'Haloli', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-243', 'Z.P.School Bhoirpada', 'Chahade', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-244', 'Z.P.School Padghe Kolipada', 'Umroli', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-245', 'Z.P.School Navapada', 'Navali', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-246', 'Z.P.School Vavepada', 'Navali', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-247', 'Z.P.School Vakadi', 'Katale', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-248', 'Z.P.School Kukade', 'Mahagaon', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-249', 'Z.P.School Nane', 'Gorhe', 'Wada', 'Palghar', 'Maharashtra'),
  ('s-250', 'Z.P.School Peth Rajani', 'Peth Ranjani', 'Wada', 'Palghar', 'Maharashtra'),
  ('s-251', 'Z.P.School Aaswe Savarpada', 'Aashagad', 'Dahanu', 'Palghar', 'Maharashtra'),
  ('s-252', 'Z.P.School Aamgaon Thakarpada', 'Aamgaon', 'Talasari', 'Palghar', 'Maharashtra'),
  ('s-253', 'Z.P.School Nihe', 'Katale', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-254', 'Z.P.School Vandivali', 'Vandivali', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-255', 'Z.P.School Aakegavhan', 'Kirat', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-256', 'Z.P.School Haloli', 'Haloli', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-257', 'Z.P.School Lalthane', 'Lalthane', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-258', 'GOVT. Aashram School Takvhal', 'Manor', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-259', 'Z.P.School Masvan', 'Maswan', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-260', 'Z.P.School Valvipada', 'Valvipada', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-261', 'Z.P.School Panjare', 'Nagzari', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-262', 'Z.P. School, Gyalanpada', 'Ganjad', 'Dahanu', 'Palghar', 'Maharashtra'),
  ('s-263', 'Z.P.School Jamshet Kamdipada', 'Aashagad', 'Dahanu', 'Palghar', 'Maharashtra'),
  ('s-264', 'Z.P.School Dabhon Patilpada', 'Dabhon', 'Dahanu', 'Palghar', 'Maharashtra'),
  ('s-265', 'Z.P.School Sagdev Khadkipada', 'Sagdeo', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-266', 'Z.P.School Tambdipada', 'Chilhar', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-267', 'Z.P.School Tolipada', 'Chilhar', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-268', 'Z.P.School Davrepada', 'Chilhar', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-269', 'Z.P.School Gavlipada', 'Chilhar', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-270', 'Z.P.School Dongarmal', 'Velgaon', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-271', 'Z.P.School Bhuklepada', 'Haloli', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-272', 'Z.P.School Kude Patilpada', 'Haloli', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-273', 'Z.P.School Khadkona', 'Haloli', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-274', 'Z.P.School Ghatalpada', 'Haloli', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-275', 'Z.P.School Khutal', 'Haloli', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-276', 'Z.P.School Dhanvipada', 'Haloli', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-277', 'ZP Purn Prathamik Adarsh Shala Purngad', 'Purngad', 'Ratnagiri', 'Ratnagiri', 'Maharashtra'),
  ('s-278', 'ZP Purn Prathamik Shala Pomendi', 'Pomendi', 'Ratnagiri', 'Ratnagiri', 'Maharashtra'),
  ('s-279', 'Z.P.School Astan No.1', 'Astan', 'Khed', 'Ratnagiri', 'Maharashtra'),
  ('s-280', 'Z.P.School Bochalpada', 'Chilhar', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-281', 'ZP Adarsh School Kaluste', 'Kaluste', 'Chiplun', 'Ratnagiri', 'Maharashtra'),
  ('s-282', 'Z.P.Adarsh Marathi School Pisai', 'Pisai', 'Dapoli', 'Ratnagiri', 'Maharashtra'),
  ('s-283', 'RZP School, Gondghar', 'Mhasala', 'Mhasala', 'Raigad', 'Maharashtra'),
  ('s-284', 'Raigad ZP Marathi School Valvati', 'Vakavati', 'Shrivardhan', 'Raigad', 'Maharashtra'),
  ('s-285', 'Z.P.School Varoti Valvipada (Kasa)', 'Kasai', 'Dahanu', 'Palghar', 'Maharashtra'),
  ('s-286', 'Z.P.School Shiroshi', 'Shiroshi', 'Jawhar', 'Palghar', 'Maharashtra'),
  ('s-287', 'Z.P.School Bhatpada', 'Vasai', 'Vasai', 'Palghar', 'Maharashtra'),
  ('s-288', 'Z.P.School Gharatpada', 'Manor', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-289', 'Z.P.School Devkhop Thalekarpada', 'Devkhop', 'Palghar', 'Palghar', 'Maharashtra'),
  ('s-290', 'Z.P.School Kesarjawalga', 'Kesarjawalga', 'Omerga', 'Dharashiv', 'Maharashtra'),
  ('s-291', 'Z.P.School Talmod', 'Talmod', 'Omerga', 'Dharashiv', 'Maharashtra'),
  ('s-292', 'Z.P.School Aanandnagar', 'Aanandnagar', 'Omerga', 'Dharashiv', 'Maharashtra'),
  ('s-293', 'Z.P.School Mulaj', 'Mulaj', 'Omerga', 'Dharashiv', 'Maharashtra'),
  ('s-294', 'Z.P.School Jagaji', 'Jagaji', 'Omerga', 'Dharashiv', 'Maharashtra'),
  ('s-295', 'Z.P.School Omerga', 'Omerga', 'Omerga', 'Dharashiv', 'Maharashtra'),
  ('s-296', 'Z.P.School Bhatangli', 'Bhatangali', 'Omerga', 'Dharashiv', 'Maharashtra'),
  ('s-297', 'Z.P.School Dhanuri', 'Dhanuri', 'Lohara', 'Dharashiv', 'Maharashtra'),
  ('s-298', 'Z.P.School Ieet', 'Ieet', 'Lohara', 'Dharashiv', 'Maharashtra'),
  ('s-299', 'Z.P.School Jawala', 'Jawala', 'Bhoom', 'Dharashiv', 'Maharashtra'),
  ('s-300', 'Z.P.School Kukkadgaon', 'Kukkadgaon', 'Paranda', 'Dharashiv', 'Maharashtra'),
  ('s-301', 'Z.P.School Masala', 'Masala', 'Paranda', 'Dharashiv', 'Maharashtra'),
  ('s-302', 'Z.P.School Sonari', 'Sonari', 'Tuljapur', 'Dharashiv', 'Maharashtra'),
  ('s-303', 'Z.P.School Patharud', 'Patharud', 'Paranda', 'Dharashiv', 'Maharashtra'),
  ('s-304', 'Z.P.School Paranda', 'Paranda', 'Paranda', 'Dharashiv', 'Maharashtra'),
  ('s-305', 'Z.P.School Patoda', 'Patoda', 'Dharashiv', 'Dharashiv', 'Maharashtra'),
  ('s-306', 'Z.P.School Pargaon', 'Pargaon', 'Washi', 'Dharashiv', 'Maharashtra'),
  ('s-307', 'Z.P.School Kaneri', 'Kaneri', 'Washi', 'Dharashiv', 'Maharashtra'),
  ('s-308', 'Z.P.School Para', 'Para', 'Washi', 'Dharashiv', 'Maharashtra'),
  ('s-309', 'Z.P.School Samarkundi', 'Samarkundi', 'Washi', 'Dharashiv', 'Maharashtra'),
  ('s-310', 'Z.P.School Aashta Bhoom', 'Ashta Bhoom', 'Bhoom', 'Dharashiv', 'Maharashtra'),
  ('s-311', 'Z.P.School Vadgaon', 'Vadgaon', 'Dharashiv', 'Dharashiv', 'Maharashtra'),
  ('s-312', 'Z.P.School Sanja', 'Sanja', 'Dharashiv', 'Dharashiv', 'Maharashtra'),
  ('s-313', 'Z.P.School Washi', 'Washi', 'Washi', 'Dharashiv', 'Maharashtra'),
  ('s-314', 'Z.P.School Naldurg', 'Naldurg', 'Tuljapur', 'Dharashiv', 'Maharashtra'),
  ('s-315', 'Z.P.School Khamaswadi', 'Khamaswadi', 'Kalamb', 'Dharashiv', 'Maharashtra'),
  ('s-316', 'Z.P.School Shiradhon', 'Shiradhon', 'Kalamb', 'Dharashiv', 'Maharashtra'),
  ('s-317', 'Z.P.School Itkur', 'Itkur', 'Kalamb', 'Dharashiv', 'Maharashtra'),
  ('s-318', 'Z.P.School Naigaon', 'Naigaon', 'Kalamb', 'Dharashiv', 'Maharashtra'),
  ('s-319', 'Z.P.School Kaudgaon', 'Kaudgaon', 'Paranda', 'Dharashiv', 'Maharashtra'),
  ('s-320', 'Z.P.School Govardhanwadi No.1', 'Govardhanwadi', 'Dharashiv', 'Dharashiv', 'Maharashtra'),
  ('s-321', 'Z.P. School Ambi', 'Ambi', 'Haveli', 'Pune', 'Maharashtra'),
  ('s-322', 'Z.P. School Kashal', 'Kashal', 'Haveli', 'Pune', 'Maharashtra'),
  ('s-323', 'Nursinha Highschool, Old Sangvi', 'Sangvi', 'Haveli', 'Pune', 'Maharashtra'),
  ('s-324', 'Z.P. School Lonikand', 'Lonikand', 'Haveli', 'Pune', 'Maharashtra'),
  ('s-325', 'Basu Vidhyalay Lonikand', 'Lonikand', 'Haveli', 'Pune', 'Maharashtra'),
  ('s-326', 'Z.P. School Bakori', 'Bakori', 'Haveli', 'Pune', 'Maharashtra'),
  ('s-327', 'Z.P. School Waysewadi', 'Waysewadi', 'Indapur', 'Pune', 'Maharashtra'),
  ('s-328', 'Z.P. School Ashoknagar', 'Ashoknagar', 'Indapur', 'Pune', 'Maharashtra'),
  ('s-329', 'Z.P. School Mhaski', 'Mhaski', 'Vaijapur', 'Chh.Sambhajinagar', 'Maharashtra'),
  ('s-330', 'Z.P. School Talwada', 'Talwada', 'Vaijapur', 'Chh.Sambhajinagar', 'Maharashtra'),
  ('s-331', 'Z.P. School Sadegaon', 'Sadegaon', 'Parbhani', 'Parbhani', 'Maharashtra'),
  ('s-332', 'Z.P. School Lokarwadi', 'Lokarwadi', 'Sonpeth', 'Parbhani', 'Maharashtra'),
  ('s-333', 'Z.P. School Rui(Limba)', 'Rui Limba', 'Beed', 'Beed', 'Maharashtra'),
  ('s-334', 'Z.P. School Ashtha Harinarayan', 'Ashtha Harinarayan', 'Ashti', 'Beed', 'Maharashtra'),
  ('s-335', 'Z.P. School Daunapur', 'Daunapur', 'Parli', 'Beed', 'Maharashtra'),
  ('s-336', 'Z.P. School Nathra', 'Nathra', 'Parli', 'Beed', 'Maharashtra'),
  ('s-337', 'Z.P. School, Sakud', 'Sakud', 'Ambajogai', 'Beed', 'Maharashtra'),
  ('s-338', 'Z.P. School, Poos', 'Poos', 'Ambajogai', 'Beed', 'Maharashtra'),
  ('s-339', 'Z.P. School Maindwadi', 'Mahindwadi', 'Parali Vaijanath', 'Beed', 'Maharashtra'),
  ('s-340', 'Z.P. School Khatkewasti', 'Khatkewasti', 'Phaltan', 'Satara', 'Maharashtra'),
  ('s-341', 'RZP Chandavalewadi School', 'Chandaylewadi', 'Uran', 'Raigad', 'Maharashtra'),
  ('s-342', 'RZP Chirnerwadi School', 'Chirnerwadi', 'Uran', 'Raigad', 'Maharashtra'),
  ('s-343', 'RZP School Gavthan', 'Gavthan', 'Uran', 'Raigad', 'Maharashtra'),
  ('s-344', 'RZP Primary School Jambhulpada', 'Jambhulpada', 'Uran', 'Raigad', 'Maharashtra'),
  ('s-345', 'RZP School Khoproliwadi', 'Khoproliwadi', 'Uran', 'Raigad', 'Maharashtra'),
  ('s-346', 'RZP School Punadewadi', 'Punadewadi', 'Uran', 'Raigad', 'Maharashtra'),
  ('s-347', 'RZP School Veshwiwadi', 'Veshwiwadi', 'Uran', 'Raigad', 'Maharashtra'),
  ('s-348', 'Nanasaheb Dharmadhikari School Girls', 'Uran', 'Uran', 'Raigad', 'Maharashtra'),
  ('s-349', 'RZP School Mulekhand', 'Mulekhand', 'Uran', 'Raigad', 'Maharashtra'),
  ('s-350', 'RZP School Nagaon', 'Nagaon', 'Uran', 'Raigad', 'Maharashtra'),
  ('s-351', 'RZP School Navin Sheva', 'Navin Sheva', 'Uran', 'Raigad', 'Maharashtra'),
  ('s-352', 'RZP School Sheve Koliwada', 'Sheva Koliwada', 'Uran', 'Raigad', 'Maharashtra'),
  ('s-353', 'RZP School Daurnagar', 'Daurnagar', 'Uran', 'Raigad', 'Maharashtra'),
  ('s-354', 'RZP School Kaladhonda', 'Kaladhonda', 'Uran', 'Raigad', 'Maharashtra'),
  ('s-355', 'RZP School Kondhari', 'Kondhari', 'Uran', 'Raigad', 'Maharashtra'),
  ('s-356', 'RZP School Ranwad', 'Ranwad', 'Uran', 'Raigad', 'Maharashtra'),
  ('s-357', 'Dronagiri Highschool', 'Uran/Dronagiri', 'Uran', 'Raigad', 'Maharashtra'),
  ('s-358', 'Mora Municipal School', 'Mora', 'Uran', 'Raigad', 'Maharashtra'),
  ('s-359', 'Abhyudaynagar School', 'Abhyudaynagar', 'Mumbai', 'Mumbai', 'Maharashtra'),
  ('s-360', 'Mangirdevi Anganwadi', 'Mangirdevi', 'Uran', 'Raigad', 'Maharashtra'),
  ('s-361', 'Badamwadi Anganawadi', 'Badaamwadi', 'Uran', 'Raigad', 'Maharashtra'),
  ('s-362', 'Chanje Dronagiri Anganwadi', 'Chanje Dronagiri', 'Uran', 'Raigad', 'Maharashtra'),
  ('s-363', 'Z.P.School Wathar', 'Wathar', 'Karad', 'Satara', 'Maharashtra'),
  ('s-364', 'Kulgaon School No.1 Belvali, Badlapur', 'Kulgaon', 'Shahapur', 'Thane', 'Maharashtra'),
  ('s-365', 'Z.P.School Jangalwasti', 'Jangalwasti', 'Vaijapur', 'Chh.Sambhajinagar', 'Maharashtra'),
  ('s-366', 'Z.P.School Wadebolhai', 'Wadebolhai', 'Maval', 'Pune', 'Maharashtra'),
  ('s-367', 'Z.P.School Markal', 'Markal', 'Khed', 'Pune', 'Maharashtra'),
  ('s-368', 'Saint Hildas Girls School', 'Swargate', 'Maval', 'Pune', 'Maharashtra'),
  ('s-369', 'Z.P.School Ghotkulewadi', 'Ghotkulewadi', 'Maval', 'Pune', 'Maharashtra'),
  ('s-370', 'Haji Abdul Majid Leader Urdu Girls Primary School', 'Nagpur City', 'Nagpur', 'Nagpur', 'Maharashtra'),
  ('s-371', 'G. M. Banatwala Primary School', 'Nagpur City', 'Nagpur', 'Nagpur', 'Maharashtra'),
  ('s-372', 'Vivekanand Primary and Secondary School', 'Nagpur City', 'Nagpur', 'Nagpur', 'Maharashtra'),
  ('s-373', 'Kapil Nagar Hindi Uchh Primary School', 'Nagpur City', 'Nagpur', 'Nagpur', 'Maharashtra'),
  ('s-374', 'Nayapura Hindi Upper Primary School', 'Nagpur City', 'Nagpur', 'Nagpur', 'Maharashtra'),
  ('s-375', 'Elaben Mehta Taldeo Mahabaleshwar', 'Taldeo', 'Mahabaleshwar', 'Satara', 'Maharashtra'),
  ('s-376', 'Z.P.School Kalhat', 'Kalhat', 'Maval', 'Pune', 'Maharashtra'),
  ('s-377', 'Z.P.School Sate', 'Sate', 'Maval', 'Pune', 'Maharashtra'),
  ('s-378', 'Sevadham Aashram Malegaon', 'Malegaon', 'Maval', 'Pune', 'Maharashtra'),
  ('s-379', 'Z.P.School Rajapuri', 'Rajapuri', 'Maval', 'Pune', 'Maharashtra'),
  ('s-380', 'Kamla Neharu Hindi Vidyalaya', 'PCMC', 'PCMC', 'Pune', 'Maharashtra'),
  ('s-381', 'Dyandeep Vidyalaya Nandwal', 'Nandwal', 'Shahapur', 'Thane', 'Maharashtra'),
  ('s-382', 'Z.P. School Darakwadi', 'Darakwadi', 'Rajguru Nagar', 'Pune', 'Maharashtra'),
  ('s-383', 'Zilla Parishad Primary School Kuravli', 'Kuravli', 'Phaltan', 'Satara', 'Maharashtra'),
  ('s-384', 'Chinchwad Badhir Mook Vidyalay Pune', 'Nigdi', 'Maval', 'Pune', 'Maharashtra'),
  ('s-385', 'Sant Sai English High School', 'Bhosari', 'Maval', 'Pune', 'Maharashtra'),
  ('s-386', 'Yashwantrao Chavan Primary and Secondary School', 'Dighi Bhosari', 'Maval', 'Pune', 'Maharashtra'),
  ('s-387', 'Zilla Parishad Primary School Kankwadi', 'Kankwadi', 'Maval', 'Pune', 'Maharashtra'),
  ('s-388', 'Zilla Parishad Primary School Urse', 'Urse', 'Maval', 'Pune', 'Maharashtra'),
  ('s-389', 'Zilla Parishad Primary School Shindevasti', 'Shindevasti', 'Maval', 'Pune', 'Maharashtra'),
  ('s-390', 'Zilla Parishad Primary School Bhongavli', 'Bhongavli', 'Bhor', 'Pune', 'Maharashtra'),
  ('s-391', 'Swargeeya Vithal Tupe Smart Learning EMSS', 'Malwadi Hadapsar', 'Maval', 'Pune', 'Maharashtra'),
  ('s-392', 'Zilla Parishad Primary School Adhale Khurd', 'Adhale Khurd', 'Maval', 'Pune', 'Maharashtra'),
  ('s-393', 'Zilla Parishad Primary School Adhale Budruk', 'Adhale Budruk', 'Maval', 'Pune', 'Maharashtra'),
  ('s-394', 'Zilla Parishad Primary School Doane', 'Doane', 'Maval', 'Pune', 'Maharashtra'),
  ('s-395', 'Zilla Parishad Primary School Divad', 'Divad', 'Maval', 'Pune', 'Maharashtra'),
  ('s-396', 'Zilla Parishad Primary School Ovale', 'Ovale', 'Maval', 'Pune', 'Maharashtra'),
  ('s-397', 'Ma.na.pa. School No. 1 (Boys)', 'Lohagaon', 'Maval', 'Pune', 'Maharashtra'),
  ('s-398', 'Ma.na.pa. School No. 2 (Girls)', 'Lohagaon', 'Maval', 'Pune', 'Maharashtra'),
  ('s-399', 'Zilla Parishad Primary School Shivane', 'Shivane', 'Maval', 'Pune', 'Maharashtra'),
  ('s-400', 'Jila Parishad Prathmik School, Gohre Budruk', 'Gohre Budruk', 'Maval', 'Pune', 'Maharashtra'),
  ('s-401', 'Jila Parishad Prathmik School Zalanwadi', 'Zalanwadi', 'Maval', 'Pune', 'Maharashtra'),
  ('s-402', 'Jila Parishad Prathmik School Donaje', 'Donaje', 'Maval', 'Pune', 'Maharashtra'),
  ('s-403', 'Jila Parishad School Khamgaon Maval', 'Khamgaon Maval', 'Maval', 'Pune', 'Maharashtra'),
  ('s-404', 'Jila Parishad Prathmik School Markal', 'Markal', 'Maval', 'Pune', 'Maharashtra'),
  ('s-405', 'Jila Parishad Prathmik School Perane', 'Perane', 'Maval', 'Pune', 'Maharashtra'),
  ('s-406', 'Jila Parishad Prathmik School Tulapur', 'Tulapur', 'Maval', 'Pune', 'Maharashtra'),
  ('s-407', 'Jila Parishad Prathmik School Parandwadi', 'Parandwadi', 'Maval', 'Pune', 'Maharashtra'),
  ('s-408', 'Jila Parishad Prathmik School Ozarde', 'Ozarde', 'Maval', 'Pune', 'Maharashtra'),
  ('s-409', 'Jila Parishad Prathmik School Kalhat', 'Kalhat', 'Maval', 'Pune', 'Maharashtra'),
  ('s-410', 'Jila Parishad Prathmik School Ghotkulewadi', 'Ghotkulewadi', 'Maval', 'Pune', 'Maharashtra'),
  ('s-411', 'Jila Parishad Prathmik School Bramhanwadi', 'Bramhanwadi (Baur)', 'Maval', 'Pune', 'Maharashtra'),
  ('s-412', 'Jila Parishad Prathmik School Vaghapur', 'Vaghapur', 'Purandhar', 'Pune', 'Maharashtra'),
  ('s-413', 'Jila Parishad Prathmik School Pargaon Memane', 'Pargaon Memane', 'Purandhar', 'Pune', 'Maharashtra'),
  ('s-414', 'Jila Parishad Prathmik School Kutwalwadi', 'Kutwalwadi', 'Purandhar', 'Pune', 'Maharashtra'),
  ('s-415', 'Jila Parishad Prathmik School Supe No. 1', 'Supe', 'Baramati', 'Pune', 'Maharashtra'),
  ('s-416', 'Jila Parishad Prathmik School Supe No. 2', 'Supe', 'Baramati', 'Pune', 'Maharashtra'),
  ('s-417', 'Jila Parishad Prathmik School Borkarwadi', 'Borkarwadi', 'Baramati', 'Pune', 'Maharashtra'),
  ('s-418', 'Jila Parishad Prathmik School Zhirkhelwasti', 'Zhirkhelwasti', 'Mulshi', 'Pune', 'Maharashtra')
ON CONFLICT (id) DO UPDATE SET
  school_name = EXCLUDED.school_name,
  village = EXCLUDED.village,
  taluka = EXCLUDED.taluka,
  district = EXCLUDED.district,
  state = EXCLUDED.state;
